/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmailSendResponseAllOfData } from './EmailSendResponseAllOfData';
import {
    EmailSendResponseAllOfDataFromJSON,
    EmailSendResponseAllOfDataFromJSONTyped,
    EmailSendResponseAllOfDataToJSON,
} from './EmailSendResponseAllOfData';

/**
 * 
 * @export
 * @interface EmailSendResponse
 */
export interface EmailSendResponse {
    /**
     * 
     * @type {number}
     * @memberof EmailSendResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof EmailSendResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSendResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmailSendResponse
     */
    success?: boolean;
    /**
     * 
     * @type {EmailSendResponseAllOfData}
     * @memberof EmailSendResponse
     */
    data?: EmailSendResponseAllOfData;
}

/**
 * Check if a given object implements the EmailSendResponse interface.
 */
export function instanceOfEmailSendResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailSendResponseFromJSON(json: any): EmailSendResponse {
    return EmailSendResponseFromJSONTyped(json, false);
}

export function EmailSendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : EmailSendResponseAllOfDataFromJSON(json['data']),
    };
}

export function EmailSendResponseToJSON(value?: EmailSendResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': EmailSendResponseAllOfDataToJSON(value.data),
    };
}

