/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSendResponseAllOfData
 */
export interface EmailSendResponseAllOfData {
    /**
     * 
     * @type {boolean}
     * @memberof EmailSendResponseAllOfData
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailSendResponseAllOfData
     */
    response?: string;
    /**
     * 
     * @type {number}
     * @memberof EmailSendResponseAllOfData
     */
    messageId?: number;
    /**
     * 
     * @type {number}
     * @memberof EmailSendResponseAllOfData
     */
    sendRecordId?: number;
}

/**
 * Check if a given object implements the EmailSendResponseAllOfData interface.
 */
export function instanceOfEmailSendResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailSendResponseAllOfDataFromJSON(json: any): EmailSendResponseAllOfData {
    return EmailSendResponseAllOfDataFromJSONTyped(json, false);
}

export function EmailSendResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'response': !exists(json, 'response') ? undefined : json['response'],
        'messageId': !exists(json, 'messageId') ? undefined : json['messageId'],
        'sendRecordId': !exists(json, 'sendRecordId') ? undefined : json['sendRecordId'],
    };
}

export function EmailSendResponseAllOfDataToJSON(value?: EmailSendResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'response': value.response,
        'messageId': value.messageId,
        'sendRecordId': value.sendRecordId,
    };
}

