/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSendWithTemplateRequest
 */
export interface EmailSendWithTemplateRequest {
    /**
     * 
     * @type {number}
     * @memberof EmailSendWithTemplateRequest
     */
    templateId?: number;
    /**
     * 
     * @type {string}
     * @memberof EmailSendWithTemplateRequest
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSendWithTemplateRequest
     */
    receiver: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSendWithTemplateRequest
     */
    additionalProperties?: string;
}

/**
 * Check if a given object implements the EmailSendWithTemplateRequest interface.
 */
export function instanceOfEmailSendWithTemplateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "receiver" in value;

    return isInstance;
}

export function EmailSendWithTemplateRequestFromJSON(json: any): EmailSendWithTemplateRequest {
    return EmailSendWithTemplateRequestFromJSONTyped(json, false);
}

export function EmailSendWithTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendWithTemplateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'templateId': !exists(json, 'templateId') ? undefined : json['templateId'],
        'sender': json['sender'],
        'receiver': json['receiver'],
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : json['additionalProperties'],
    };
}

export function EmailSendWithTemplateRequestToJSON(value?: EmailSendWithTemplateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'templateId': value.templateId,
        'sender': value.sender,
        'receiver': value.receiver,
        'additionalProperties': value.additionalProperties,
    };
}

