/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface MessageGetByIdResponse
 */
export interface MessageGetByIdResponse {
    /**
     * 
     * @type {number}
     * @memberof MessageGetByIdResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageGetByIdResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageGetByIdResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageGetByIdResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Message}
     * @memberof MessageGetByIdResponse
     */
    data?: Message;
}

/**
 * Check if a given object implements the MessageGetByIdResponse interface.
 */
export function instanceOfMessageGetByIdResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MessageGetByIdResponseFromJSON(json: any): MessageGetByIdResponse {
    return MessageGetByIdResponseFromJSONTyped(json, false);
}

export function MessageGetByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageGetByIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : MessageFromJSON(json['data']),
    };
}

export function MessageGetByIdResponseToJSON(value?: MessageGetByIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': MessageToJSON(value.data),
    };
}

