/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    notifyType?: number;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    receiver?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    templateId?: number;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    templateParameter?: string;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    count?: number;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Message interface.
 */
export function instanceOfMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MessageFromJSON(json: any): Message {
    return MessageFromJSONTyped(json, false);
}

export function MessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Message {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'notifyType': !exists(json, 'notifyType') ? undefined : json['notifyType'],
        'receiver': !exists(json, 'receiver') ? undefined : json['receiver'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'templateId': !exists(json, 'templateId') ? undefined : json['templateId'],
        'templateParameter': !exists(json, 'templateParameter') ? undefined : json['templateParameter'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function MessageToJSON(value?: Message | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'notifyType': value.notifyType,
        'receiver': value.receiver,
        'subject': value.subject,
        'content': value.content,
        'templateId': value.templateId,
        'templateParameter': value.templateParameter,
        'status': value.status,
        'count': value.count,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

