/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Passageway
 */
export interface Passageway {
    /**
     * 
     * @type {number}
     * @memberof Passageway
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Passageway
     */
    uuid?: string;
    /**
     * 
     * @type {number}
     * @memberof Passageway
     */
    notifyType?: number;
    /**
     * 
     * @type {number}
     * @memberof Passageway
     */
    range?: number;
    /**
     * 
     * @type {number}
     * @memberof Passageway
     */
    status?: number;
    /**
     * 
     * @type {Date}
     * @memberof Passageway
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Passageway
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Passageway interface.
 */
export function instanceOfPassageway(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PassagewayFromJSON(json: any): Passageway {
    return PassagewayFromJSONTyped(json, false);
}

export function PassagewayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Passageway {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'notifyType': !exists(json, 'notifyType') ? undefined : json['notifyType'],
        'range': !exists(json, 'range') ? undefined : json['range'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function PassagewayToJSON(value?: Passageway | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'notifyType': value.notifyType,
        'range': value.range,
        'status': value.status,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

