/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Passageway } from './Passageway';
import {
    PassagewayFromJSON,
    PassagewayFromJSONTyped,
    PassagewayToJSON,
} from './Passageway';

/**
 * 
 * @export
 * @interface PassagewayGetResponse
 */
export interface PassagewayGetResponse {
    /**
     * 
     * @type {number}
     * @memberof PassagewayGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof PassagewayGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof PassagewayGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PassagewayGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Passageway>}
     * @memberof PassagewayGetResponse
     */
    data?: Array<Passageway>;
}

/**
 * Check if a given object implements the PassagewayGetResponse interface.
 */
export function instanceOfPassagewayGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PassagewayGetResponseFromJSON(json: any): PassagewayGetResponse {
    return PassagewayGetResponseFromJSONTyped(json, false);
}

export function PassagewayGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassagewayGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(PassagewayFromJSON)),
    };
}

export function PassagewayGetResponseToJSON(value?: PassagewayGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(PassagewayToJSON)),
    };
}

