/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendRecord
 */
export interface SendRecord {
    /**
     * 
     * @type {number}
     * @memberof SendRecord
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof SendRecord
     */
    messageId?: number;
    /**
     * 
     * @type {number}
     * @memberof SendRecord
     */
    passagewayId?: number;
    /**
     * 
     * @type {number}
     * @memberof SendRecord
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof SendRecord
     */
    responseCode?: number;
    /**
     * 
     * @type {string}
     * @memberof SendRecord
     */
    responseContent?: string;
    /**
     * 
     * @type {Date}
     * @memberof SendRecord
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SendRecord
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the SendRecord interface.
 */
export function instanceOfSendRecord(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendRecordFromJSON(json: any): SendRecord {
    return SendRecordFromJSONTyped(json, false);
}

export function SendRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'messageId': !exists(json, 'messageId') ? undefined : json['messageId'],
        'passagewayId': !exists(json, 'passagewayId') ? undefined : json['passagewayId'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'responseCode': !exists(json, 'responseCode') ? undefined : json['responseCode'],
        'responseContent': !exists(json, 'responseContent') ? undefined : json['responseContent'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function SendRecordToJSON(value?: SendRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'messageId': value.messageId,
        'passagewayId': value.passagewayId,
        'status': value.status,
        'responseCode': value.responseCode,
        'responseContent': value.responseContent,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

