/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SendRecord } from './SendRecord';
import {
    SendRecordFromJSON,
    SendRecordFromJSONTyped,
    SendRecordToJSON,
} from './SendRecord';

/**
 * 
 * @export
 * @interface SendRecordGetByIdResponse
 */
export interface SendRecordGetByIdResponse {
    /**
     * 
     * @type {number}
     * @memberof SendRecordGetByIdResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof SendRecordGetByIdResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SendRecordGetByIdResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SendRecordGetByIdResponse
     */
    success?: boolean;
    /**
     * 
     * @type {SendRecord}
     * @memberof SendRecordGetByIdResponse
     */
    data?: SendRecord;
}

/**
 * Check if a given object implements the SendRecordGetByIdResponse interface.
 */
export function instanceOfSendRecordGetByIdResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendRecordGetByIdResponseFromJSON(json: any): SendRecordGetByIdResponse {
    return SendRecordGetByIdResponseFromJSONTyped(json, false);
}

export function SendRecordGetByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRecordGetByIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : SendRecordFromJSON(json['data']),
    };
}

export function SendRecordGetByIdResponseToJSON(value?: SendRecordGetByIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': SendRecordToJSON(value.data),
    };
}

