/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
} from './Template';

/**
 * 
 * @export
 * @interface TemplateGetResponse
 */
export interface TemplateGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TemplateGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Template>}
     * @memberof TemplateGetResponse
     */
    data?: Array<Template>;
}

/**
 * Check if a given object implements the TemplateGetResponse interface.
 */
export function instanceOfTemplateGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplateGetResponseFromJSON(json: any): TemplateGetResponse {
    return TemplateGetResponseFromJSONTyped(json, false);
}

export function TemplateGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TemplateFromJSON)),
    };
}

export function TemplateGetResponseToJSON(value?: TemplateGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TemplateToJSON)),
    };
}

