/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateUpdateRequest
 */
export interface TemplateUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateRequest
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateRequest
     */
    receiver: string;
}

/**
 * Check if a given object implements the TemplateUpdateRequest interface.
 */
export function instanceOfTemplateUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "receiver" in value;

    return isInstance;
}

export function TemplateUpdateRequestFromJSON(json: any): TemplateUpdateRequest {
    return TemplateUpdateRequestFromJSONTyped(json, false);
}

export function TemplateUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'sender': json['sender'],
        'receiver': json['receiver'],
    };
}

export function TemplateUpdateRequestToJSON(value?: TemplateUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
        'sender': value.sender,
        'receiver': value.receiver,
    };
}

