/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateAddRequest
 */
export interface TemplateAddRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateAddRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateAddRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateAddRequest
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateAddRequest
     */
    receiver: string;
}

/**
 * Check if a given object implements the TemplateAddRequest interface.
 */
export function instanceOfTemplateAddRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "receiver" in value;

    return isInstance;
}

export function TemplateAddRequestFromJSON(json: any): TemplateAddRequest {
    return TemplateAddRequestFromJSONTyped(json, false);
}

export function TemplateAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateAddRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'sender': json['sender'],
        'receiver': json['receiver'],
    };
}

export function TemplateAddRequestToJSON(value?: TemplateAddRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
        'sender': value.sender,
        'receiver': value.receiver,
    };
}

