/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
} from './Template';

/**
 * 
 * @export
 * @interface TemplateGetByIdResponse
 */
export interface TemplateGetByIdResponse {
    /**
     * 
     * @type {number}
     * @memberof TemplateGetByIdResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetByIdResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateGetByIdResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TemplateGetByIdResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Template}
     * @memberof TemplateGetByIdResponse
     */
    data?: Template;
}

/**
 * Check if a given object implements the TemplateGetByIdResponse interface.
 */
export function instanceOfTemplateGetByIdResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplateGetByIdResponseFromJSON(json: any): TemplateGetByIdResponse {
    return TemplateGetByIdResponseFromJSONTyped(json, false);
}

export function TemplateGetByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateGetByIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : TemplateFromJSON(json['data']),
    };
}

export function TemplateGetByIdResponseToJSON(value?: TemplateGetByIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': TemplateToJSON(value.data),
    };
}

