/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CardOrder,
  CardOrderConfirmRequest,
  CardOrderConfirmResponse,
  CardOrderGetResponse,
  CardOrderPageRequest,
  CardOrderPageResponse,
  CardOrderRemarkRequest,
  CardOrderRemarkResponse,
  CardOrderShipRequest,
  CardOrderShipResponse,
} from '../models/index';
import {
    CardOrderFromJSON,
    CardOrderToJSON,
    CardOrderConfirmRequestFromJSON,
    CardOrderConfirmRequestToJSON,
    CardOrderConfirmResponseFromJSON,
    CardOrderConfirmResponseToJSON,
    CardOrderGetResponseFromJSON,
    CardOrderGetResponseToJSON,
    CardOrderPageRequestFromJSON,
    CardOrderPageRequestToJSON,
    CardOrderPageResponseFromJSON,
    CardOrderPageResponseToJSON,
    CardOrderRemarkRequestFromJSON,
    CardOrderRemarkRequestToJSON,
    CardOrderRemarkResponseFromJSON,
    CardOrderRemarkResponseToJSON,
    CardOrderShipRequestFromJSON,
    CardOrderShipRequestToJSON,
    CardOrderShipResponseFromJSON,
    CardOrderShipResponseToJSON,
} from '../models/index';

export interface CardOrderConfirmOperationRequest {
    cardOrderId: number;
    cardOrderConfirmRequest: CardOrderConfirmRequest;
}

export interface CardOrderGetRequest {
    cardOrder: CardOrder;
}

export interface CardOrderPageOperationRequest {
    cardOrderPageRequest: CardOrderPageRequest;
}

export interface CardOrderRemarkOperationRequest {
    cardOrderId: number;
    cardOrderRemarkRequest: CardOrderRemarkRequest;
}

export interface CardOrderShipOperationRequest {
    cardOrderId: number;
    cardOrderShipRequest: CardOrderShipRequest;
}

/**
 * 
 */
export class CardOrderApi extends runtime.BaseAPI {

    /**
     * 確認付款狀態
     */
    async cardOrderConfirmRaw(requestParameters: CardOrderConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderConfirmResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderConfirm.');
        }

        if (requestParameters.cardOrderConfirmRequest === null || requestParameters.cardOrderConfirmRequest === undefined) {
            throw new runtime.RequiredError('cardOrderConfirmRequest','Required parameter requestParameters.cardOrderConfirmRequest was null or undefined when calling cardOrderConfirm.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}/confirm`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderConfirmRequestToJSON(requestParameters.cardOrderConfirmRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderConfirmResponseFromJSON(jsonValue));
    }

    /**
     * 確認付款狀態
     */
    async cardOrderConfirm(requestParameters: CardOrderConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderConfirmResponse> {
        const response = await this.cardOrderConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得卡片訂單
     */
    async cardOrderGetRaw(requestParameters: CardOrderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderGetResponse>> {
        if (requestParameters.cardOrder === null || requestParameters.cardOrder === undefined) {
            throw new runtime.RequiredError('cardOrder','Required parameter requestParameters.cardOrder was null or undefined when calling cardOrderGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderToJSON(requestParameters.cardOrder),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得卡片訂單
     */
    async cardOrderGet(requestParameters: CardOrderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderGetResponse> {
        const response = await this.cardOrderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得卡片訂單分頁
     */
    async cardOrderPageRaw(requestParameters: CardOrderPageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderPageResponse>> {
        if (requestParameters.cardOrderPageRequest === null || requestParameters.cardOrderPageRequest === undefined) {
            throw new runtime.RequiredError('cardOrderPageRequest','Required parameter requestParameters.cardOrderPageRequest was null or undefined when calling cardOrderPage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderPageRequestToJSON(requestParameters.cardOrderPageRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderPageResponseFromJSON(jsonValue));
    }

    /**
     * 取得卡片訂單分頁
     */
    async cardOrderPage(requestParameters: CardOrderPageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderPageResponse> {
        const response = await this.cardOrderPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 備註訂單
     */
    async cardOrderRemarkRaw(requestParameters: CardOrderRemarkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderRemarkResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderRemark.');
        }

        if (requestParameters.cardOrderRemarkRequest === null || requestParameters.cardOrderRemarkRequest === undefined) {
            throw new runtime.RequiredError('cardOrderRemarkRequest','Required parameter requestParameters.cardOrderRemarkRequest was null or undefined when calling cardOrderRemark.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}/remark`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderRemarkRequestToJSON(requestParameters.cardOrderRemarkRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderRemarkResponseFromJSON(jsonValue));
    }

    /**
     * 備註訂單
     */
    async cardOrderRemark(requestParameters: CardOrderRemarkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderRemarkResponse> {
        const response = await this.cardOrderRemarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 發貨
     */
    async cardOrderShipRaw(requestParameters: CardOrderShipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderShipResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderShip.');
        }

        if (requestParameters.cardOrderShipRequest === null || requestParameters.cardOrderShipRequest === undefined) {
            throw new runtime.RequiredError('cardOrderShipRequest','Required parameter requestParameters.cardOrderShipRequest was null or undefined when calling cardOrderShip.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}/ship`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderShipRequestToJSON(requestParameters.cardOrderShipRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderShipResponseFromJSON(jsonValue));
    }

    /**
     * 發貨
     */
    async cardOrderShip(requestParameters: CardOrderShipOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderShipResponse> {
        const response = await this.cardOrderShipRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
