/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SystemUser,
  SystemUserGetResponse,
} from '../models/index';
import {
    SystemUserFromJSON,
    SystemUserToJSON,
    SystemUserGetResponseFromJSON,
    SystemUserGetResponseToJSON,
} from '../models/index';

export interface SystemUserGetRequest {
    systemUser: SystemUser;
}

/**
 * 
 */
export class SystemUserApi extends runtime.BaseAPI {

    /**
     * 取得系統用戶資料
     */
    async systemUserGetRaw(requestParameters: SystemUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemUserGetResponse>> {
        if (requestParameters.systemUser === null || requestParameters.systemUser === undefined) {
            throw new runtime.RequiredError('systemUser','Required parameter requestParameters.systemUser was null or undefined when calling systemUserGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/systemUser`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: SystemUserToJSON(requestParameters.systemUser),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemUserGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得系統用戶資料
     */
    async systemUserGet(requestParameters: SystemUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemUserGetResponse> {
        const response = await this.systemUserGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
