/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
} from './Id';

/**
 * 
 * @export
 * @interface AgencyAddResponse
 */
export interface AgencyAddResponse {
    /**
     * 
     * @type {number}
     * @memberof AgencyAddResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyAddResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencyAddResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencyAddResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Id}
     * @memberof AgencyAddResponse
     */
    data?: Id;
}

/**
 * Check if a given object implements the AgencyAddResponse interface.
 */
export function instanceOfAgencyAddResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyAddResponseFromJSON(json: any): AgencyAddResponse {
    return AgencyAddResponseFromJSONTyped(json, false);
}

export function AgencyAddResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyAddResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : IdFromJSON(json['data']),
    };
}

export function AgencyAddResponseToJSON(value?: AgencyAddResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': IdToJSON(value.data),
    };
}

