/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AgencyPlan } from './AgencyPlan';
import {
    AgencyPlanFromJSON,
    AgencyPlanFromJSONTyped,
    AgencyPlanToJSON,
} from './AgencyPlan';

/**
 * 
 * @export
 * @interface AgencyPlanGetResponse
 */
export interface AgencyPlanGetResponse {
    /**
     * 
     * @type {number}
     * @memberof AgencyPlanGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlanGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlanGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencyPlanGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<AgencyPlan>}
     * @memberof AgencyPlanGetResponse
     */
    data?: Array<AgencyPlan>;
}

/**
 * Check if a given object implements the AgencyPlanGetResponse interface.
 */
export function instanceOfAgencyPlanGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyPlanGetResponseFromJSON(json: any): AgencyPlanGetResponse {
    return AgencyPlanGetResponseFromJSONTyped(json, false);
}

export function AgencyPlanGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyPlanGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AgencyPlanFromJSON)),
    };
}

export function AgencyPlanGetResponseToJSON(value?: AgencyPlanGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AgencyPlanToJSON)),
    };
}

