/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agency
 */
export interface Agency {
    /**
     * 
     * @type {number}
     * @memberof Agency
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Agency
     */
    countryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    nationalPhoneNumber?: string;
    /**
     * 1:active 2:inactive
     * @type {number}
     * @memberof Agency
     */
    agencyStatus?: number;
    /**
     * 1:phone 2:email 3:username
     * @type {number}
     * @memberof Agency
     */
    registrationMethod?: number;
    /**
     * 
     * @type {Date}
     * @memberof Agency
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Agency
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Agency interface.
 */
export function instanceOfAgency(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyFromJSON(json: any): Agency {
    return AgencyFromJSONTyped(json, false);
}

export function AgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'nationalPhoneNumber': !exists(json, 'nationalPhoneNumber') ? undefined : json['nationalPhoneNumber'],
        'agencyStatus': !exists(json, 'agencyStatus') ? undefined : json['agencyStatus'],
        'registrationMethod': !exists(json, 'registrationMethod') ? undefined : json['registrationMethod'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function AgencyToJSON(value?: Agency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'countryCode': value.countryCode,
        'nationalPhoneNumber': value.nationalPhoneNumber,
        'agencyStatus': value.agencyStatus,
        'registrationMethod': value.registrationMethod,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

