/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Agency } from './Agency';
import {
    AgencyFromJSON,
    AgencyFromJSONTyped,
    AgencyToJSON,
} from './Agency';

/**
 * 
 * @export
 * @interface AgencyGetResponse
 */
export interface AgencyGetResponse {
    /**
     * 
     * @type {number}
     * @memberof AgencyGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencyGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencyGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Agency>}
     * @memberof AgencyGetResponse
     */
    data?: Array<Agency>;
}

/**
 * Check if a given object implements the AgencyGetResponse interface.
 */
export function instanceOfAgencyGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyGetResponseFromJSON(json: any): AgencyGetResponse {
    return AgencyGetResponseFromJSONTyped(json, false);
}

export function AgencyGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AgencyFromJSON)),
    };
}

export function AgencyGetResponseToJSON(value?: AgencyGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AgencyToJSON)),
    };
}

