/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AgencyStatus = {
    None: 'none',
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type AgencyStatus = typeof AgencyStatus[keyof typeof AgencyStatus];


export function AgencyStatusFromJSON(json: any): AgencyStatus {
    return AgencyStatusFromJSONTyped(json, false);
}

export function AgencyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyStatus {
    return json as AgencyStatus;
}

export function AgencyStatusToJSON(value?: AgencyStatus | null): any {
    return value as any;
}

