/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgencyPlan
 */
export interface AgencyPlan {
    /**
     * 
     * @type {number}
     * @memberof AgencyPlan
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AgencyPlan
     */
    agencyId?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlan
     */
    agencyName?: string;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {number}
     * @memberof AgencyPlan
     */
    cardAssociation?: number;
    /**
     * in percentage
     * @type {number}
     * @memberof AgencyPlan
     */
    discount?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlan
     */
    referralCode?: string;
    /**
     * 1:active 2:inactive
     * @type {number}
     * @memberof AgencyPlan
     */
    planStatus?: number;
    /**
     * 1:phone 2:email 3:username
     * @type {number}
     * @memberof AgencyPlan
     */
    registrationMethod?: number;
    /**
     * 
     * @type {Date}
     * @memberof AgencyPlan
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AgencyPlan
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AgencyPlan interface.
 */
export function instanceOfAgencyPlan(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyPlanFromJSON(json: any): AgencyPlan {
    return AgencyPlanFromJSONTyped(json, false);
}

export function AgencyPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyPlan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'agencyId': !exists(json, 'agencyId') ? undefined : json['agencyId'],
        'agencyName': !exists(json, 'agencyName') ? undefined : json['agencyName'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'referralCode': !exists(json, 'referralCode') ? undefined : json['referralCode'],
        'planStatus': !exists(json, 'planStatus') ? undefined : json['planStatus'],
        'registrationMethod': !exists(json, 'registrationMethod') ? undefined : json['registrationMethod'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function AgencyPlanToJSON(value?: AgencyPlan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'agencyId': value.agencyId,
        'agencyName': value.agencyName,
        'cardAssociation': value.cardAssociation,
        'discount': value.discount,
        'referralCode': value.referralCode,
        'planStatus': value.planStatus,
        'registrationMethod': value.registrationMethod,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

