/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Agency } from './Agency';
import {
    AgencyFromJSON,
    AgencyFromJSONTyped,
    AgencyToJSON,
} from './Agency';

/**
 * 
 * @export
 * @interface AgencyUpdateResponse
 */
export interface AgencyUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof AgencyUpdateResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyUpdateResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencyUpdateResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencyUpdateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Agency}
     * @memberof AgencyUpdateResponse
     */
    data?: Agency;
}

/**
 * Check if a given object implements the AgencyUpdateResponse interface.
 */
export function instanceOfAgencyUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyUpdateResponseFromJSON(json: any): AgencyUpdateResponse {
    return AgencyUpdateResponseFromJSONTyped(json, false);
}

export function AgencyUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : AgencyFromJSON(json['data']),
    };
}

export function AgencyUpdateResponseToJSON(value?: AgencyUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': AgencyToJSON(value.data),
    };
}

