/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AgencyPlan } from './AgencyPlan';
import {
    AgencyPlanFromJSON,
    AgencyPlanFromJSONTyped,
    AgencyPlanToJSON,
} from './AgencyPlan';

/**
 * 
 * @export
 * @interface AgencyPlanUpdateResponse
 */
export interface AgencyPlanUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof AgencyPlanUpdateResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlanUpdateResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencyPlanUpdateResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencyPlanUpdateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {AgencyPlan}
     * @memberof AgencyPlanUpdateResponse
     */
    data?: AgencyPlan;
}

/**
 * Check if a given object implements the AgencyPlanUpdateResponse interface.
 */
export function instanceOfAgencyPlanUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AgencyPlanUpdateResponseFromJSON(json: any): AgencyPlanUpdateResponse {
    return AgencyPlanUpdateResponseFromJSONTyped(json, false);
}

export function AgencyPlanUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencyPlanUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : AgencyPlanFromJSON(json['data']),
    };
}

export function AgencyPlanUpdateResponseToJSON(value?: AgencyPlanUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': AgencyPlanToJSON(value.data),
    };
}

