---
productDescriptionGetResponse:
  allOf:
    - $ref: "../../schemas.yml#/schemas/result"
    - type: object
      properties:
        data:
          type: array
          items:
            "$ref": "../../schemas.yml#/schemas/productDescription"
    