/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderConfirmRequest
 */
export interface CardOrderConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof CardOrderConfirmRequest
     */
    remark?: string;
}

/**
 * Check if a given object implements the CardOrderConfirmRequest interface.
 */
export function instanceOfCardOrderConfirmRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderConfirmRequestFromJSON(json: any): CardOrderConfirmRequest {
    return CardOrderConfirmRequestFromJSONTyped(json, false);
}

export function CardOrderConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderConfirmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
    };
}

export function CardOrderConfirmRequestToJSON(value?: CardOrderConfirmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remark': value.remark,
    };
}

