/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardOrder } from './CardOrder';
import {
    CardOrderFromJSON,
    CardOrderFromJSONTyped,
    CardOrderToJSON,
} from './CardOrder';

/**
 * 
 * @export
 * @interface CardOrderPageResponseAllOfData
 */
export interface CardOrderPageResponseAllOfData {
    /**
     * 
     * @type {number}
     * @memberof CardOrderPageResponseAllOfData
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderPageResponseAllOfData
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderPageResponseAllOfData
     */
    current?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderPageResponseAllOfData
     */
    pages?: number;
    /**
     * 
     * @type {Array<CardOrder>}
     * @memberof CardOrderPageResponseAllOfData
     */
    records?: Array<CardOrder>;
}

/**
 * Check if a given object implements the CardOrderPageResponseAllOfData interface.
 */
export function instanceOfCardOrderPageResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderPageResponseAllOfDataFromJSON(json: any): CardOrderPageResponseAllOfData {
    return CardOrderPageResponseAllOfDataFromJSONTyped(json, false);
}

export function CardOrderPageResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderPageResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'current': !exists(json, 'current') ? undefined : json['current'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(CardOrderFromJSON)),
    };
}

export function CardOrderPageResponseAllOfDataToJSON(value?: CardOrderPageResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'size': value.size,
        'current': value.current,
        'pages': value.pages,
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(CardOrderToJSON)),
    };
}

