/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderRemarkRequest
 */
export interface CardOrderRemarkRequest {
    /**
     * 
     * @type {string}
     * @memberof CardOrderRemarkRequest
     */
    remark?: string;
}

/**
 * Check if a given object implements the CardOrderRemarkRequest interface.
 */
export function instanceOfCardOrderRemarkRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderRemarkRequestFromJSON(json: any): CardOrderRemarkRequest {
    return CardOrderRemarkRequestFromJSONTyped(json, false);
}

export function CardOrderRemarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderRemarkRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
    };
}

export function CardOrderRemarkRequestToJSON(value?: CardOrderRemarkRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remark': value.remark,
    };
}

