/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardOrder } from './CardOrder';
import {
    CardOrderFromJSON,
    CardOrderFromJSONTyped,
    CardOrderToJSON,
} from './CardOrder';

/**
 * 
 * @export
 * @interface CardOrderGetResponse
 */
export interface CardOrderGetResponse {
    /**
     * 
     * @type {number}
     * @memberof CardOrderGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardOrderGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<CardOrder>}
     * @memberof CardOrderGetResponse
     */
    data?: Array<CardOrder>;
}

/**
 * Check if a given object implements the CardOrderGetResponse interface.
 */
export function instanceOfCardOrderGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderGetResponseFromJSON(json: any): CardOrderGetResponse {
    return CardOrderGetResponseFromJSONTyped(json, false);
}

export function CardOrderGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CardOrderFromJSON)),
    };
}

export function CardOrderGetResponseToJSON(value?: CardOrderGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CardOrderToJSON)),
    };
}

