/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderShipRequest
 */
export interface CardOrderShipRequest {
    /**
     * 
     * @type {string}
     * @memberof CardOrderShipRequest
     */
    shippingOrderNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderShipRequest
     */
    shippingVendor?: number;
    /**
     * 
     * @type {Date}
     * @memberof CardOrderShipRequest
     */
    shippedAt?: Date;
}

/**
 * Check if a given object implements the CardOrderShipRequest interface.
 */
export function instanceOfCardOrderShipRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderShipRequestFromJSON(json: any): CardOrderShipRequest {
    return CardOrderShipRequestFromJSONTyped(json, false);
}

export function CardOrderShipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderShipRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shippingOrderNumber': !exists(json, 'shippingOrderNumber') ? undefined : json['shippingOrderNumber'],
        'shippingVendor': !exists(json, 'shippingVendor') ? undefined : json['shippingVendor'],
        'shippedAt': !exists(json, 'shippedAt') ? undefined : (new Date(json['shippedAt'])),
    };
}

export function CardOrderShipRequestToJSON(value?: CardOrderShipRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shippingOrderNumber': value.shippingOrderNumber,
        'shippingVendor': value.shippingVendor,
        'shippedAt': value.shippedAt === undefined ? undefined : (value.shippedAt.toISOString()),
    };
}

