/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtToken
 */
export interface JwtToken {
    /**
     * 
     * @type {string}
     * @memberof JwtToken
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtToken
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the JwtToken interface.
 */
export function instanceOfJwtToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JwtTokenFromJSON(json: any): JwtToken {
    return JwtTokenFromJSONTyped(json, false);
}

export function JwtTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function JwtTokenToJSON(value?: JwtToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}

