/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemUser
 */
export interface SystemUser {
    /**
     * 
     * @type {number}
     * @memberof SystemUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemUser
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemUser
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemUser
     */
    userName?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemUser
     */
    status?: number;
    /**
     * 
     * @type {Date}
     * @memberof SystemUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SystemUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof SystemUser
     */
    updatedBy?: number;
}

/**
 * Check if a given object implements the SystemUser interface.
 */
export function instanceOfSystemUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SystemUserFromJSON(json: any): SystemUser {
    return SystemUserFromJSONTyped(json, false);
}

export function SystemUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : json['updatedBy'],
    };
}

export function SystemUserToJSON(value?: SystemUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'account': value.account,
        'password': value.password,
        'userName': value.userName,
        'status': value.status,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'updatedBy': value.updatedBy,
    };
}

