/* tslint:disable */
/* eslint-disable */
/**
 * management base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemUser } from './SystemUser';
import {
    SystemUserFromJSON,
    SystemUserFromJSONTyped,
    SystemUserToJSON,
} from './SystemUser';

/**
 * 
 * @export
 * @interface SystemUserGetResponse
 */
export interface SystemUserGetResponse {
    /**
     * 
     * @type {number}
     * @memberof SystemUserGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemUserGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemUserGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SystemUserGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<SystemUser>}
     * @memberof SystemUserGetResponse
     */
    data?: Array<SystemUser>;
}

/**
 * Check if a given object implements the SystemUserGetResponse interface.
 */
export function instanceOfSystemUserGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SystemUserGetResponseFromJSON(json: any): SystemUserGetResponse {
    return SystemUserGetResponseFromJSONTyped(json, false);
}

export function SystemUserGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemUserGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SystemUserFromJSON)),
    };
}

export function SystemUserGetResponseToJSON(value?: SystemUserGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SystemUserToJSON)),
    };
}

