/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CardProduct,
  CardProductAddResponse,
  CardProductGetResponse,
} from '../models/index';
import {
    CardProductFromJSON,
    CardProductToJSON,
    CardProductAddResponseFromJSON,
    CardProductAddResponseToJSON,
    CardProductGetResponseFromJSON,
    CardProductGetResponseToJSON,
} from '../models/index';

export interface CardProductAddRequest {
    cardProduct: CardProduct;
}

export interface CardProductGetRequest {
    cardProduct: CardProduct;
}

/**
 * 
 */
export class CardProductApi extends runtime.BaseAPI {

    /**
     * 新增卡片產品
     */
    async cardProductAddRaw(requestParameters: CardProductAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardProductAddResponse>> {
        if (requestParameters.cardProduct === null || requestParameters.cardProduct === undefined) {
            throw new runtime.RequiredError('cardProduct','Required parameter requestParameters.cardProduct was null or undefined when calling cardProductAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardProduct`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardProductToJSON(requestParameters.cardProduct),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardProductAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增卡片產品
     */
    async cardProductAdd(requestParameters: CardProductAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardProductAddResponse> {
        const response = await this.cardProductAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得卡片產品
     */
    async cardProductGetRaw(requestParameters: CardProductGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardProductGetResponse>> {
        if (requestParameters.cardProduct === null || requestParameters.cardProduct === undefined) {
            throw new runtime.RequiredError('cardProduct','Required parameter requestParameters.cardProduct was null or undefined when calling cardProductGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardProduct`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardProductToJSON(requestParameters.cardProduct),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardProductGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得卡片產品
     */
    async cardProductGet(requestParameters: CardProductGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardProductGetResponse> {
        const response = await this.cardProductGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
