/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CardIssuer,
  CardIssuerGetResponse,
} from '../models/index';
import {
    CardIssuerFromJSON,
    CardIssuerToJSON,
    CardIssuerGetResponseFromJSON,
    CardIssuerGetResponseToJSON,
} from '../models/index';

export interface CardIssuerGetRequest {
    cardIssuer: CardIssuer;
}

/**
 * 
 */
export class CardIssuerApi extends runtime.BaseAPI {

    /**
     * 取得發卡商
     */
    async cardIssuerGetRaw(requestParameters: CardIssuerGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardIssuerGetResponse>> {
        if (requestParameters.cardIssuer === null || requestParameters.cardIssuer === undefined) {
            throw new runtime.RequiredError('cardIssuer','Required parameter requestParameters.cardIssuer was null or undefined when calling cardIssuerGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardIssuer`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardIssuerToJSON(requestParameters.cardIssuer),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardIssuerGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得發卡商
     */
    async cardIssuerGet(requestParameters: CardIssuerGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardIssuerGetResponse> {
        const response = await this.cardIssuerGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
