/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductDisplayAllRequest,
  ProductDisplayAllResponse,
  ProductDisplayRequest,
  ProductDisplayResponse,
} from '../models/index';
import {
    ProductDisplayAllRequestFromJSON,
    ProductDisplayAllRequestToJSON,
    ProductDisplayAllResponseFromJSON,
    ProductDisplayAllResponseToJSON,
    ProductDisplayRequestFromJSON,
    ProductDisplayRequestToJSON,
    ProductDisplayResponseFromJSON,
    ProductDisplayResponseToJSON,
} from '../models/index';

export interface ProductDisplayOperationRequest {
    productDisplayRequest: ProductDisplayRequest;
}

export interface ProductDisplayAllOperationRequest {
    productDisplayAllRequest: ProductDisplayAllRequest;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     * 展示產品
     */
    async productDisplayRaw(requestParameters: ProductDisplayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDisplayResponse>> {
        if (requestParameters.productDisplayRequest === null || requestParameters.productDisplayRequest === undefined) {
            throw new runtime.RequiredError('productDisplayRequest','Required parameter requestParameters.productDisplayRequest was null or undefined when calling productDisplay.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/product/display`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: ProductDisplayRequestToJSON(requestParameters.productDisplayRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDisplayResponseFromJSON(jsonValue));
    }

    /**
     * 展示產品
     */
    async productDisplay(requestParameters: ProductDisplayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDisplayResponse> {
        const response = await this.productDisplayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 展示所有推薦產品
     */
    async productDisplayAllRaw(requestParameters: ProductDisplayAllOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDisplayAllResponse>> {
        if (requestParameters.productDisplayAllRequest === null || requestParameters.productDisplayAllRequest === undefined) {
            throw new runtime.RequiredError('productDisplayAllRequest','Required parameter requestParameters.productDisplayAllRequest was null or undefined when calling productDisplayAll.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/product/displayAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: ProductDisplayAllRequestToJSON(requestParameters.productDisplayAllRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDisplayAllResponseFromJSON(jsonValue));
    }

    /**
     * 展示所有推薦產品
     */
    async productDisplayAll(requestParameters: ProductDisplayAllOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDisplayAllResponse> {
        const response = await this.productDisplayAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
