/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductDescription,
  ProductDescriptionAddResponse,
  ProductDescriptionGetResponse,
} from '../models/index';
import {
    ProductDescriptionFromJSON,
    ProductDescriptionToJSON,
    ProductDescriptionAddResponseFromJSON,
    ProductDescriptionAddResponseToJSON,
    ProductDescriptionGetResponseFromJSON,
    ProductDescriptionGetResponseToJSON,
} from '../models/index';

export interface ProductDescriptionAddRequest {
    productDescription: ProductDescription;
}

export interface ProductDescriptionGetRequest {
    productDescription: ProductDescription;
}

/**
 * 
 */
export class ProductDescriptionApi extends runtime.BaseAPI {

    /**
     * 取得產品說明
     */
    async productDescriptionAddRaw(requestParameters: ProductDescriptionAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDescriptionAddResponse>> {
        if (requestParameters.productDescription === null || requestParameters.productDescription === undefined) {
            throw new runtime.RequiredError('productDescription','Required parameter requestParameters.productDescription was null or undefined when calling productDescriptionAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/productDescription`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductDescriptionToJSON(requestParameters.productDescription),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDescriptionAddResponseFromJSON(jsonValue));
    }

    /**
     * 取得產品說明
     */
    async productDescriptionAdd(requestParameters: ProductDescriptionAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDescriptionAddResponse> {
        const response = await this.productDescriptionAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得產品說明
     */
    async productDescriptionGetRaw(requestParameters: ProductDescriptionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDescriptionGetResponse>> {
        if (requestParameters.productDescription === null || requestParameters.productDescription === undefined) {
            throw new runtime.RequiredError('productDescription','Required parameter requestParameters.productDescription was null or undefined when calling productDescriptionGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/productDescription`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: ProductDescriptionToJSON(requestParameters.productDescription),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDescriptionGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得產品說明
     */
    async productDescriptionGet(requestParameters: ProductDescriptionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDescriptionGetResponse> {
        const response = await this.productDescriptionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
