/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardOrder } from './CardOrder';
import {
    CardOrderFromJSON,
    CardOrderFromJSONTyped,
    CardOrderToJSON,
} from './CardOrder';

/**
 * 
 * @export
 * @interface CardOrderLatestExpiredGetResponse
 */
export interface CardOrderLatestExpiredGetResponse {
    /**
     * 
     * @type {number}
     * @memberof CardOrderLatestExpiredGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderLatestExpiredGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderLatestExpiredGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardOrderLatestExpiredGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {CardOrder}
     * @memberof CardOrderLatestExpiredGetResponse
     */
    data?: CardOrder;
}

/**
 * Check if a given object implements the CardOrderLatestExpiredGetResponse interface.
 */
export function instanceOfCardOrderLatestExpiredGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderLatestExpiredGetResponseFromJSON(json: any): CardOrderLatestExpiredGetResponse {
    return CardOrderLatestExpiredGetResponseFromJSONTyped(json, false);
}

export function CardOrderLatestExpiredGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderLatestExpiredGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : CardOrderFromJSON(json['data']),
    };
}

export function CardOrderLatestExpiredGetResponseToJSON(value?: CardOrderLatestExpiredGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': CardOrderToJSON(value.data),
    };
}

