/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardOrderPageResponseAllOfData } from './CardOrderPageResponseAllOfData';
import {
    CardOrderPageResponseAllOfDataFromJSON,
    CardOrderPageResponseAllOfDataFromJSONTyped,
    CardOrderPageResponseAllOfDataToJSON,
} from './CardOrderPageResponseAllOfData';

/**
 * 
 * @export
 * @interface CardOrderPageResponse
 */
export interface CardOrderPageResponse {
    /**
     * 
     * @type {number}
     * @memberof CardOrderPageResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderPageResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderPageResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardOrderPageResponse
     */
    success?: boolean;
    /**
     * 
     * @type {CardOrderPageResponseAllOfData}
     * @memberof CardOrderPageResponse
     */
    data?: CardOrderPageResponseAllOfData;
}

/**
 * Check if a given object implements the CardOrderPageResponse interface.
 */
export function instanceOfCardOrderPageResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderPageResponseFromJSON(json: any): CardOrderPageResponse {
    return CardOrderPageResponseFromJSONTyped(json, false);
}

export function CardOrderPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderPageResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : CardOrderPageResponseAllOfDataFromJSON(json['data']),
    };
}

export function CardOrderPageResponseToJSON(value?: CardOrderPageResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': CardOrderPageResponseAllOfDataToJSON(value.data),
    };
}

