/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderRepayRequest
 */
export interface CardOrderRepayRequest {
    /**
     * 
     * @type {number}
     * @memberof CardOrderRepayRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the CardOrderRepayRequest interface.
 */
export function instanceOfCardOrderRepayRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderRepayRequestFromJSON(json: any): CardOrderRepayRequest {
    return CardOrderRepayRequestFromJSONTyped(json, false);
}

export function CardOrderRepayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderRepayRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function CardOrderRepayRequestToJSON(value?: CardOrderRepayRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

