/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderLatestExpiredGetRequest
 */
export interface CardOrderLatestExpiredGetRequest {
    /**
     * 
     * @type {number}
     * @memberof CardOrderLatestExpiredGetRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the CardOrderLatestExpiredGetRequest interface.
 */
export function instanceOfCardOrderLatestExpiredGetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderLatestExpiredGetRequestFromJSON(json: any): CardOrderLatestExpiredGetRequest {
    return CardOrderLatestExpiredGetRequestFromJSONTyped(json, false);
}

export function CardOrderLatestExpiredGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderLatestExpiredGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function CardOrderLatestExpiredGetRequestToJSON(value?: CardOrderLatestExpiredGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

