/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderApplyRequest
 */
export interface CardOrderApplyRequest {
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    userFirstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    userLastName?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    userGender?: number;
    /**
     * 國籍編碼(ISO 3166-1) 中國:CHN 新加坡:SGP 台灣:TWN
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    userNationCode?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    userCountryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    userNationalPhoneNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    cardProductId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    referralCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    emailFromAgency?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    countryCodeFromAgency?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    nationalPhoneNumberFromAgency?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    agencyPlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    orderAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    shippingCity?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    shippingNationCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    shippingPostalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    shippingAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderApplyRequest
     */
    shippingCountryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    shippingNationalPhoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderApplyRequest
     */
    remark?: string;
}

/**
 * Check if a given object implements the CardOrderApplyRequest interface.
 */
export function instanceOfCardOrderApplyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderApplyRequestFromJSON(json: any): CardOrderApplyRequest {
    return CardOrderApplyRequestFromJSONTyped(json, false);
}

export function CardOrderApplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderApplyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'userFirstName': !exists(json, 'userFirstName') ? undefined : json['userFirstName'],
        'userLastName': !exists(json, 'userLastName') ? undefined : json['userLastName'],
        'userGender': !exists(json, 'userGender') ? undefined : json['userGender'],
        'userNationCode': !exists(json, 'userNationCode') ? undefined : json['userNationCode'],
        'userCountryCode': !exists(json, 'userCountryCode') ? undefined : json['userCountryCode'],
        'userNationalPhoneNumber': !exists(json, 'userNationalPhoneNumber') ? undefined : json['userNationalPhoneNumber'],
        'cardProductId': !exists(json, 'cardProductId') ? undefined : json['cardProductId'],
        'referralCode': !exists(json, 'referralCode') ? undefined : json['referralCode'],
        'emailFromAgency': !exists(json, 'emailFromAgency') ? undefined : json['emailFromAgency'],
        'countryCodeFromAgency': !exists(json, 'countryCodeFromAgency') ? undefined : json['countryCodeFromAgency'],
        'nationalPhoneNumberFromAgency': !exists(json, 'nationalPhoneNumberFromAgency') ? undefined : json['nationalPhoneNumberFromAgency'],
        'agencyPlanId': !exists(json, 'agencyPlanId') ? undefined : json['agencyPlanId'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'orderAmount': !exists(json, 'orderAmount') ? undefined : json['orderAmount'],
        'shippingCity': !exists(json, 'shippingCity') ? undefined : json['shippingCity'],
        'shippingNationCode': !exists(json, 'shippingNationCode') ? undefined : json['shippingNationCode'],
        'shippingPostalCode': !exists(json, 'shippingPostalCode') ? undefined : json['shippingPostalCode'],
        'shippingAddress': !exists(json, 'shippingAddress') ? undefined : json['shippingAddress'],
        'shippingCountryCode': !exists(json, 'shippingCountryCode') ? undefined : json['shippingCountryCode'],
        'shippingNationalPhoneNumber': !exists(json, 'shippingNationalPhoneNumber') ? undefined : json['shippingNationalPhoneNumber'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
    };
}

export function CardOrderApplyRequestToJSON(value?: CardOrderApplyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'userFirstName': value.userFirstName,
        'userLastName': value.userLastName,
        'userGender': value.userGender,
        'userNationCode': value.userNationCode,
        'userCountryCode': value.userCountryCode,
        'userNationalPhoneNumber': value.userNationalPhoneNumber,
        'cardProductId': value.cardProductId,
        'referralCode': value.referralCode,
        'emailFromAgency': value.emailFromAgency,
        'countryCodeFromAgency': value.countryCodeFromAgency,
        'nationalPhoneNumberFromAgency': value.nationalPhoneNumberFromAgency,
        'agencyPlanId': value.agencyPlanId,
        'cryptocurrency': value.cryptocurrency,
        'orderAmount': value.orderAmount,
        'shippingCity': value.shippingCity,
        'shippingNationCode': value.shippingNationCode,
        'shippingPostalCode': value.shippingPostalCode,
        'shippingAddress': value.shippingAddress,
        'shippingCountryCode': value.shippingCountryCode,
        'shippingNationalPhoneNumber': value.shippingNationalPhoneNumber,
        'remark': value.remark,
    };
}

