/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardOrderIsLatest
 */
export interface CardOrderIsLatest {
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    orderNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    transferId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    transferOrderNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    cardProductId?: number;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    cardAssociation?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    userFirstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    userLastName?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    userGender?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    agencyPlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    agencyName?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    referralCode?: string;
    /**
     * 1:phone 2:email 3:username
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    agencyRegistrationMethod?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    countryCodeFromAgency?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    nationalPhoneNumberFromAgency?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    emailFromAgency?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    orderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    finalOrderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    receivedAmount?: number;
    /**
     * 百分比顯示
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    shippingCountryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingNationalPhoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingCity?: string;
    /**
     * 國籍編碼(ISO 3166-1) 中國:CHN 新加坡:SGP 台灣:TWN
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingNationCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingPostalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingAddress?: string;
    /**
     * 1:創建中 2:待付款 3:付款中 4:完成付款 5:付款失敗 6:超時 7:金額不符 8:重新付款
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    paymentStatus?: number;
    /**
     * 1:creatingShipping 2:pendingShipment 3:shipped 4:failedToCreateShipping
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    shippingStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    shippingOrderNumber?: string;
    /**
     * 物流公司 1:DHL 2:FedEx
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    shippingVendor?: number;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    remark?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    agreement?: string;
    /**
     * 
     * @type {string}
     * @memberof CardOrderIsLatest
     */
    redirectLink?: string;
    /**
     * 
     * @type {number}
     * @memberof CardOrderIsLatest
     */
    cardId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CardOrderIsLatest
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardOrderIsLatest
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardOrderIsLatest
     */
    paymentDueAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardOrderIsLatest
     */
    shippedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CardOrderIsLatest
     */
    isLatest?: boolean;
}

/**
 * Check if a given object implements the CardOrderIsLatest interface.
 */
export function instanceOfCardOrderIsLatest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardOrderIsLatestFromJSON(json: any): CardOrderIsLatest {
    return CardOrderIsLatestFromJSONTyped(json, false);
}

export function CardOrderIsLatestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardOrderIsLatest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'orderNumber': !exists(json, 'orderNumber') ? undefined : json['orderNumber'],
        'transferId': !exists(json, 'transferId') ? undefined : json['transferId'],
        'transferOrderNumber': !exists(json, 'transferOrderNumber') ? undefined : json['transferOrderNumber'],
        'cardProductId': !exists(json, 'cardProductId') ? undefined : json['cardProductId'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'userFirstName': !exists(json, 'userFirstName') ? undefined : json['userFirstName'],
        'userLastName': !exists(json, 'userLastName') ? undefined : json['userLastName'],
        'userGender': !exists(json, 'userGender') ? undefined : json['userGender'],
        'agencyPlanId': !exists(json, 'agencyPlanId') ? undefined : json['agencyPlanId'],
        'agencyName': !exists(json, 'agencyName') ? undefined : json['agencyName'],
        'referralCode': !exists(json, 'referralCode') ? undefined : json['referralCode'],
        'agencyRegistrationMethod': !exists(json, 'agencyRegistrationMethod') ? undefined : json['agencyRegistrationMethod'],
        'countryCodeFromAgency': !exists(json, 'countryCodeFromAgency') ? undefined : json['countryCodeFromAgency'],
        'nationalPhoneNumberFromAgency': !exists(json, 'nationalPhoneNumberFromAgency') ? undefined : json['nationalPhoneNumberFromAgency'],
        'emailFromAgency': !exists(json, 'emailFromAgency') ? undefined : json['emailFromAgency'],
        'orderAmount': !exists(json, 'orderAmount') ? undefined : json['orderAmount'],
        'finalOrderAmount': !exists(json, 'finalOrderAmount') ? undefined : json['finalOrderAmount'],
        'receivedAmount': !exists(json, 'receivedAmount') ? undefined : json['receivedAmount'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'shippingCountryCode': !exists(json, 'shippingCountryCode') ? undefined : json['shippingCountryCode'],
        'shippingNationalPhoneNumber': !exists(json, 'shippingNationalPhoneNumber') ? undefined : json['shippingNationalPhoneNumber'],
        'shippingCity': !exists(json, 'shippingCity') ? undefined : json['shippingCity'],
        'shippingNationCode': !exists(json, 'shippingNationCode') ? undefined : json['shippingNationCode'],
        'shippingPostalCode': !exists(json, 'shippingPostalCode') ? undefined : json['shippingPostalCode'],
        'shippingAddress': !exists(json, 'shippingAddress') ? undefined : json['shippingAddress'],
        'paymentStatus': !exists(json, 'paymentStatus') ? undefined : json['paymentStatus'],
        'shippingStatus': !exists(json, 'shippingStatus') ? undefined : json['shippingStatus'],
        'shippingOrderNumber': !exists(json, 'shippingOrderNumber') ? undefined : json['shippingOrderNumber'],
        'shippingVendor': !exists(json, 'shippingVendor') ? undefined : json['shippingVendor'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
        'agreement': !exists(json, 'agreement') ? undefined : json['agreement'],
        'redirectLink': !exists(json, 'redirectLink') ? undefined : json['redirectLink'],
        'cardId': !exists(json, 'cardId') ? undefined : json['cardId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'paymentDueAt': !exists(json, 'paymentDueAt') ? undefined : (new Date(json['paymentDueAt'])),
        'shippedAt': !exists(json, 'shippedAt') ? undefined : (new Date(json['shippedAt'])),
        'isLatest': !exists(json, 'isLatest') ? undefined : json['isLatest'],
    };
}

export function CardOrderIsLatestToJSON(value?: CardOrderIsLatest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'orderNumber': value.orderNumber,
        'transferId': value.transferId,
        'transferOrderNumber': value.transferOrderNumber,
        'cardProductId': value.cardProductId,
        'cardAssociation': value.cardAssociation,
        'cryptocurrency': value.cryptocurrency,
        'currency': value.currency,
        'userFirstName': value.userFirstName,
        'userLastName': value.userLastName,
        'userGender': value.userGender,
        'agencyPlanId': value.agencyPlanId,
        'agencyName': value.agencyName,
        'referralCode': value.referralCode,
        'agencyRegistrationMethod': value.agencyRegistrationMethod,
        'countryCodeFromAgency': value.countryCodeFromAgency,
        'nationalPhoneNumberFromAgency': value.nationalPhoneNumberFromAgency,
        'emailFromAgency': value.emailFromAgency,
        'orderAmount': value.orderAmount,
        'finalOrderAmount': value.finalOrderAmount,
        'receivedAmount': value.receivedAmount,
        'discount': value.discount,
        'shippingCountryCode': value.shippingCountryCode,
        'shippingNationalPhoneNumber': value.shippingNationalPhoneNumber,
        'shippingCity': value.shippingCity,
        'shippingNationCode': value.shippingNationCode,
        'shippingPostalCode': value.shippingPostalCode,
        'shippingAddress': value.shippingAddress,
        'paymentStatus': value.paymentStatus,
        'shippingStatus': value.shippingStatus,
        'shippingOrderNumber': value.shippingOrderNumber,
        'shippingVendor': value.shippingVendor,
        'remark': value.remark,
        'agreement': value.agreement,
        'redirectLink': value.redirectLink,
        'cardId': value.cardId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'paymentDueAt': value.paymentDueAt === undefined ? undefined : (value.paymentDueAt.toISOString()),
        'shippedAt': value.shippedAt === undefined ? undefined : (value.shippedAt.toISOString()),
        'isLatest': value.isLatest,
    };
}

