/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cryptocurrency
 */
export interface Cryptocurrency {
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    name?: string;
}

/**
 * Check if a given object implements the Cryptocurrency interface.
 */
export function instanceOfCryptocurrency(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CryptocurrencyFromJSON(json: any): Cryptocurrency {
    return CryptocurrencyFromJSONTyped(json, false);
}

export function CryptocurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cryptocurrency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': !exists(json, 'symbol') ? undefined : json['symbol'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CryptocurrencyToJSON(value?: Cryptocurrency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'name': value.name,
    };
}

