/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferConfirmResponse
 */
export interface TransferConfirmResponse {
    /**
     * 
     * @type {number}
     * @memberof TransferConfirmResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransferConfirmResponse
     */
    success?: boolean;
    /**
     * 
     * @type {object}
     * @memberof TransferConfirmResponse
     */
    data?: object;
}

/**
 * Check if a given object implements the TransferConfirmResponse interface.
 */
export function instanceOfTransferConfirmResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferConfirmResponseFromJSON(json: any): TransferConfirmResponse {
    return TransferConfirmResponseFromJSONTyped(json, false);
}

export function TransferConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferConfirmResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function TransferConfirmResponseToJSON(value?: TransferConfirmResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data,
    };
}

