/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferConfirmRequest
 */
export interface TransferConfirmRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmRequest
     */
    defaultField?: string;
}

/**
 * Check if a given object implements the TransferConfirmRequest interface.
 */
export function instanceOfTransferConfirmRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferConfirmRequestFromJSON(json: any): TransferConfirmRequest {
    return TransferConfirmRequestFromJSONTyped(json, false);
}

export function TransferConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferConfirmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'defaultField': !exists(json, 'defaultField') ? undefined : json['defaultField'],
    };
}

export function TransferConfirmRequestToJSON(value?: TransferConfirmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'defaultField': value.defaultField,
    };
}

