/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferConfirmLog
 */
export interface TransferConfirmLog {
    /**
     * 
     * @type {number}
     * @memberof TransferConfirmLog
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferConfirmLog
     */
    accumulativeTotalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    companyOrderNo?: string;
    /**
     * 
     * @type {Date}
     * @memberof TransferConfirmLog
     */
    rechargeAccountTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof TransferConfirmLog
     */
    rechargeActualAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof TransferConfirmLog
     */
    rechargeActualCoin?: number;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    rechargeAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    rechargeDetailOrderNo?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    fromAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    txHash?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferConfirmLog
     */
    ext?: string;
    /**
     * 
     * @type {Date}
     * @memberof TransferConfirmLog
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TransferConfirmLog
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TransferConfirmLog interface.
 */
export function instanceOfTransferConfirmLog(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferConfirmLogFromJSON(json: any): TransferConfirmLog {
    return TransferConfirmLogFromJSONTyped(json, false);
}

export function TransferConfirmLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferConfirmLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'accumulativeTotalAmount': !exists(json, 'accumulativeTotalAmount') ? undefined : json['accumulativeTotalAmount'],
        'companyOrderNo': !exists(json, 'companyOrderNo') ? undefined : json['companyOrderNo'],
        'rechargeAccountTime': !exists(json, 'rechargeAccountTime') ? undefined : (new Date(json['rechargeAccountTime'])),
        'rechargeActualAmount': !exists(json, 'rechargeActualAmount') ? undefined : json['rechargeActualAmount'],
        'rechargeActualCoin': !exists(json, 'rechargeActualCoin') ? undefined : json['rechargeActualCoin'],
        'rechargeAddress': !exists(json, 'rechargeAddress') ? undefined : json['rechargeAddress'],
        'rechargeDetailOrderNo': !exists(json, 'rechargeDetailOrderNo') ? undefined : json['rechargeDetailOrderNo'],
        'fromAddress': !exists(json, 'fromAddress') ? undefined : json['fromAddress'],
        'txHash': !exists(json, 'txHash') ? undefined : json['txHash'],
        'ext': !exists(json, 'ext') ? undefined : json['ext'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TransferConfirmLogToJSON(value?: TransferConfirmLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'accumulativeTotalAmount': value.accumulativeTotalAmount,
        'companyOrderNo': value.companyOrderNo,
        'rechargeAccountTime': value.rechargeAccountTime === undefined ? undefined : (value.rechargeAccountTime.toISOString()),
        'rechargeActualAmount': value.rechargeActualAmount,
        'rechargeActualCoin': value.rechargeActualCoin,
        'rechargeAddress': value.rechargeAddress,
        'rechargeDetailOrderNo': value.rechargeDetailOrderNo,
        'fromAddress': value.fromAddress,
        'txHash': value.txHash,
        'ext': value.ext,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

