/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    orderNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    redirectLink?: string;
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    transferAmount?: number;
    /**
     * 1:deposit 2:withdraw
     * @type {number}
     * @memberof Transfer
     */
    direction?: number;
    /**
     * 1:creating 2:pending 3:processing 4:completed 5:denied 6:overdue
     * @type {number}
     * @memberof Transfer
     */
    paymentStatus?: number;
    /**
     * 
     * @type {Date}
     * @memberof Transfer
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Transfer
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Transfer interface.
 */
export function instanceOfTransfer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferFromJSON(json: any): Transfer {
    return TransferFromJSONTyped(json, false);
}

export function TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'orderNumber': !exists(json, 'orderNumber') ? undefined : json['orderNumber'],
        'redirectLink': !exists(json, 'redirectLink') ? undefined : json['redirectLink'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'transferAmount': !exists(json, 'transferAmount') ? undefined : json['transferAmount'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'paymentStatus': !exists(json, 'paymentStatus') ? undefined : json['paymentStatus'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function TransferToJSON(value?: Transfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'orderNumber': value.orderNumber,
        'redirectLink': value.redirectLink,
        'userId': value.userId,
        'cryptocurrency': value.cryptocurrency,
        'transferAmount': value.transferAmount,
        'direction': value.direction,
        'paymentStatus': value.paymentStatus,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

