/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transfer } from './Transfer';
import {
    TransferFromJSON,
    TransferFromJSONTyped,
    TransferToJSON,
} from './Transfer';

/**
 * 
 * @export
 * @interface TransferGetResponse
 */
export interface TransferGetResponse {
    /**
     * 
     * @type {number}
     * @memberof TransferGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TransferGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransferGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Transfer>}
     * @memberof TransferGetResponse
     */
    data?: Array<Transfer>;
}

/**
 * Check if a given object implements the TransferGetResponse interface.
 */
export function instanceOfTransferGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransferGetResponseFromJSON(json: any): TransferGetResponse {
    return TransferGetResponseFromJSONTyped(json, false);
}

export function TransferGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TransferFromJSON)),
    };
}

export function TransferGetResponseToJSON(value?: TransferGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TransferToJSON)),
    };
}

