/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLogoutRequestAccessToken } from './AuthLogoutRequestAccessToken';
import {
    AuthLogoutRequestAccessTokenFromJSON,
    AuthLogoutRequestAccessTokenFromJSONTyped,
    AuthLogoutRequestAccessTokenToJSON,
} from './AuthLogoutRequestAccessToken';

/**
 * 
 * @export
 * @interface AuthLogoutRequest
 */
export interface AuthLogoutRequest {
    /**
     * 
     * @type {AuthLogoutRequestAccessToken}
     * @memberof AuthLogoutRequest
     */
    accessToken?: AuthLogoutRequestAccessToken;
    /**
     * 
     * @type {AuthLogoutRequestAccessToken}
     * @memberof AuthLogoutRequest
     */
    refreshToken?: AuthLogoutRequestAccessToken;
}

/**
 * Check if a given object implements the AuthLogoutRequest interface.
 */
export function instanceOfAuthLogoutRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthLogoutRequestFromJSON(json: any): AuthLogoutRequest {
    return AuthLogoutRequestFromJSONTyped(json, false);
}

export function AuthLogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : AuthLogoutRequestAccessTokenFromJSON(json['accessToken']),
        'refreshToken': !exists(json, 'refreshToken') ? undefined : AuthLogoutRequestAccessTokenFromJSON(json['refreshToken']),
    };
}

export function AuthLogoutRequestToJSON(value?: AuthLogoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': AuthLogoutRequestAccessTokenToJSON(value.accessToken),
        'refreshToken': AuthLogoutRequestAccessTokenToJSON(value.refreshToken),
    };
}

