/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginResponse
 */
export interface AuthLoginResponse {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLoginResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AuthLoginResponse interface.
 */
export function instanceOfAuthLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthLoginResponseFromJSON(json: any): AuthLoginResponse {
    return AuthLoginResponseFromJSONTyped(json, false);
}

export function AuthLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function AuthLoginResponseToJSON(value?: AuthLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}

