/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogoutResponse
 */
export interface AuthLogoutResponse {
    /**
     * 
     * @type {number}
     * @memberof AuthLogoutResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogoutResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the AuthLogoutResponse interface.
 */
export function instanceOfAuthLogoutResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthLogoutResponseFromJSON(json: any): AuthLogoutResponse {
    return AuthLogoutResponseFromJSONTyped(json, false);
}

export function AuthLogoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function AuthLogoutResponseToJSON(value?: AuthLogoutResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
    };
}

