/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogoutRequestAccessToken
 */
export interface AuthLogoutRequestAccessToken {
    [key: string]: object | any;
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutRequestAccessToken
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthLogoutRequestAccessToken interface.
 */
export function instanceOfAuthLogoutRequestAccessToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthLogoutRequestAccessTokenFromJSON(json: any): AuthLogoutRequestAccessToken {
    return AuthLogoutRequestAccessTokenFromJSONTyped(json, false);
}

export function AuthLogoutRequestAccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutRequestAccessToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function AuthLogoutRequestAccessTokenToJSON(value?: AuthLogoutRequestAccessToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'token': value.token,
    };
}

