/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
} from './PhoneNumber';

/**
 * 
 * @export
 * @interface AuthSendVerificationCodeRequest
 */
export interface AuthSendVerificationCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSendVerificationCodeRequest
     */
    email?: string;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof AuthSendVerificationCodeRequest
     */
    phoneNumber?: PhoneNumber;
    /**
     * 驗證碼目的 1:register 2:login 3:forgetPassword
     * @type {number}
     * @memberof AuthSendVerificationCodeRequest
     */
    purpose?: number;
}

/**
 * Check if a given object implements the AuthSendVerificationCodeRequest interface.
 */
export function instanceOfAuthSendVerificationCodeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthSendVerificationCodeRequestFromJSON(json: any): AuthSendVerificationCodeRequest {
    return AuthSendVerificationCodeRequestFromJSONTyped(json, false);
}

export function AuthSendVerificationCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSendVerificationCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : PhoneNumberFromJSON(json['phoneNumber']),
        'purpose': !exists(json, 'purpose') ? undefined : json['purpose'],
    };
}

export function AuthSendVerificationCodeRequestToJSON(value?: AuthSendVerificationCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'phoneNumber': PhoneNumberToJSON(value.phoneNumber),
        'purpose': value.purpose,
    };
}

