/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCaptchaGetRequest
 */
export interface AuthCaptchaGetRequest {
    /**
     * captcha目的 1:user login 2:admin login
     * @type {number}
     * @memberof AuthCaptchaGetRequest
     */
    purpose?: number;
}

/**
 * Check if a given object implements the AuthCaptchaGetRequest interface.
 */
export function instanceOfAuthCaptchaGetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthCaptchaGetRequestFromJSON(json: any): AuthCaptchaGetRequest {
    return AuthCaptchaGetRequestFromJSONTyped(json, false);
}

export function AuthCaptchaGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCaptchaGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'purpose': !exists(json, 'purpose') ? undefined : json['purpose'],
    };
}

export function AuthCaptchaGetRequestToJSON(value?: AuthCaptchaGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'purpose': value.purpose,
    };
}

