/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    jwtId?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    audience?: string;
    /**
     * 
     * @type {Date}
     * @memberof Token
     */
    notBefore?: Date;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    issuer?: string;
    /**
     * 
     * @type {Date}
     * @memberof Token
     */
    issuedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Token
     */
    expiration?: Date;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    role?: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    caller?: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    type?: number;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'jwtId': !exists(json, 'jwtId') ? undefined : json['jwtId'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'audience': !exists(json, 'audience') ? undefined : json['audience'],
        'notBefore': !exists(json, 'notBefore') ? undefined : (new Date(json['notBefore'])),
        'issuer': !exists(json, 'issuer') ? undefined : json['issuer'],
        'issuedAt': !exists(json, 'issuedAt') ? undefined : (new Date(json['issuedAt'])),
        'expiration': !exists(json, 'expiration') ? undefined : (new Date(json['expiration'])),
        'role': !exists(json, 'role') ? undefined : json['role'],
        'caller': !exists(json, 'caller') ? undefined : json['caller'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'jwtId': value.jwtId,
        'subject': value.subject,
        'audience': value.audience,
        'notBefore': value.notBefore === undefined ? undefined : (value.notBefore.toISOString()),
        'issuer': value.issuer,
        'issuedAt': value.issuedAt === undefined ? undefined : (value.issuedAt.toISOString()),
        'expiration': value.expiration === undefined ? undefined : (value.expiration.toISOString()),
        'role': value.role,
        'caller': value.caller,
        'type': value.type,
    };
}

