/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResetPasswordRequest
 */
export interface UserResetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof UserResetPasswordRequest
     */
    oldPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResetPasswordRequest
     */
    newPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResetPasswordRequest
     */
    conformNewPassword?: string;
}

/**
 * Check if a given object implements the UserResetPasswordRequest interface.
 */
export function instanceOfUserResetPasswordRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserResetPasswordRequestFromJSON(json: any): UserResetPasswordRequest {
    return UserResetPasswordRequestFromJSONTyped(json, false);
}

export function UserResetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResetPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oldPassword': !exists(json, 'oldPassword') ? undefined : json['oldPassword'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
        'conformNewPassword': !exists(json, 'conformNewPassword') ? undefined : json['conformNewPassword'],
    };
}

export function UserResetPasswordRequestToJSON(value?: UserResetPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oldPassword': value.oldPassword,
        'newPassword': value.newPassword,
        'conformNewPassword': value.conformNewPassword,
    };
}

