/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    countryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    nationalPhoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 國籍編碼(ISO 3166-1) 中國:CHN 新加坡:SGP 台灣:TWN
     * @type {string}
     * @memberof User
     */
    nationCode?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    gender?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    agencyId?: number;
    /**
     * 1:phone 2:email 3:username
     * @type {number}
     * @memberof User
     */
    agencyRegistrationMethod?: number;
    /**
     * format:2023-12-25T05:04:03+02:00
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
    /**
     * format:2023-12-25T05:04:03+02:00
     * @type {Date}
     * @memberof User
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    countryCodeFromAgency?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    nationalPhoneNumberFromAgency?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    emailFromAgency?: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'nationalPhoneNumber': !exists(json, 'nationalPhoneNumber') ? undefined : json['nationalPhoneNumber'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'nationCode': !exists(json, 'nationCode') ? undefined : json['nationCode'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'agencyId': !exists(json, 'agencyId') ? undefined : json['agencyId'],
        'agencyRegistrationMethod': !exists(json, 'agencyRegistrationMethod') ? undefined : json['agencyRegistrationMethod'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'countryCodeFromAgency': !exists(json, 'countryCodeFromAgency') ? undefined : json['countryCodeFromAgency'],
        'nationalPhoneNumberFromAgency': !exists(json, 'nationalPhoneNumberFromAgency') ? undefined : json['nationalPhoneNumberFromAgency'],
        'emailFromAgency': !exists(json, 'emailFromAgency') ? undefined : json['emailFromAgency'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'countryCode': value.countryCode,
        'nationalPhoneNumber': value.nationalPhoneNumber,
        'password': value.password,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'nationCode': value.nationCode,
        'gender': value.gender,
        'address': value.address,
        'agencyId': value.agencyId,
        'agencyRegistrationMethod': value.agencyRegistrationMethod,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'countryCodeFromAgency': value.countryCodeFromAgency,
        'nationalPhoneNumberFromAgency': value.nationalPhoneNumberFromAgency,
        'emailFromAgency': value.emailFromAgency,
    };
}

