/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserInfoGetResponse
 */
export interface UserInfoGetResponse {
    /**
     * 
     * @type {number}
     * @memberof UserInfoGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfoGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfoGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserInfoGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {User}
     * @memberof UserInfoGetResponse
     */
    data?: User;
}

/**
 * Check if a given object implements the UserInfoGetResponse interface.
 */
export function instanceOfUserInfoGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInfoGetResponseFromJSON(json: any): UserInfoGetResponse {
    return UserInfoGetResponseFromJSONTyped(json, false);
}

export function UserInfoGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : UserFromJSON(json['data']),
    };
}

export function UserInfoGetResponseToJSON(value?: UserInfoGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': UserToJSON(value.data),
    };
}

