/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserForgetPasswordRequest
 */
export interface UserForgetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof UserForgetPasswordRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserForgetPasswordRequest
     */
    emailVerificationCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserForgetPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserForgetPasswordRequest
     */
    conformPassword?: string;
}

/**
 * Check if a given object implements the UserForgetPasswordRequest interface.
 */
export function instanceOfUserForgetPasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "emailVerificationCode" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserForgetPasswordRequestFromJSON(json: any): UserForgetPasswordRequest {
    return UserForgetPasswordRequestFromJSONTyped(json, false);
}

export function UserForgetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserForgetPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'emailVerificationCode': json['emailVerificationCode'],
        'password': json['password'],
        'conformPassword': !exists(json, 'conformPassword') ? undefined : json['conformPassword'],
    };
}

export function UserForgetPasswordRequestToJSON(value?: UserForgetPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'emailVerificationCode': value.emailVerificationCode,
        'password': value.password,
        'conformPassword': value.conformPassword,
    };
}

