/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JwtToken } from './JwtToken';
import {
    JwtTokenFromJSON,
    JwtTokenFromJSONTyped,
    JwtTokenToJSON,
} from './JwtToken';

/**
 * 
 * @export
 * @interface UserRegisterResponse
 */
export interface UserRegisterResponse {
    /**
     * 
     * @type {number}
     * @memberof UserRegisterResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserRegisterResponse
     */
    success?: boolean;
    /**
     * 
     * @type {JwtToken}
     * @memberof UserRegisterResponse
     */
    data?: JwtToken;
}

/**
 * Check if a given object implements the UserRegisterResponse interface.
 */
export function instanceOfUserRegisterResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRegisterResponseFromJSON(json: any): UserRegisterResponse {
    return UserRegisterResponseFromJSONTyped(json, false);
}

export function UserRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : JwtTokenFromJSON(json['data']),
    };
}

export function UserRegisterResponseToJSON(value?: UserRegisterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': JwtTokenToJSON(value.data),
    };
}

