/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegisterRequest
 */
export interface UserRegisterRequest {
    /**
     * max:100
     * @type {string}
     * @memberof UserRegisterRequest
     */
    email: string;
    /**
     * max:6
     * @type {string}
     * @memberof UserRegisterRequest
     */
    emailVerificationCode: string;
    /**
     * max:100
     * @type {string}
     * @memberof UserRegisterRequest
     */
    password: string;
    /**
     * max:100
     * @type {string}
     * @memberof UserRegisterRequest
     */
    confirmPassword?: string;
}

/**
 * Check if a given object implements the UserRegisterRequest interface.
 */
export function instanceOfUserRegisterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "emailVerificationCode" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserRegisterRequestFromJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestFromJSONTyped(json, false);
}

export function UserRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'emailVerificationCode': json['emailVerificationCode'],
        'password': json['password'],
        'confirmPassword': !exists(json, 'confirmPassword') ? undefined : json['confirmPassword'],
    };
}

export function UserRegisterRequestToJSON(value?: UserRegisterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'emailVerificationCode': value.emailVerificationCode,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

