/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoRequest
 */
export interface UserInfoRequest {
    /**
     * 
     * @type {number}
     * @memberof UserInfoRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the UserInfoRequest interface.
 */
export function instanceOfUserInfoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInfoRequestFromJSON(json: any): UserInfoRequest {
    return UserInfoRequestFromJSONTyped(json, false);
}

export function UserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UserInfoRequestToJSON(value?: UserInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

