/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBindRequest
 */
export interface UserBindRequest {
    /**
     * 
     * @type {string}
     * @memberof UserBindRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserBindRequest
     */
    emailVerificationCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserBindRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserBindRequest
     */
    conformPassword: string;
}

/**
 * Check if a given object implements the UserBindRequest interface.
 */
export function instanceOfUserBindRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "emailVerificationCode" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "conformPassword" in value;

    return isInstance;
}

export function UserBindRequestFromJSON(json: any): UserBindRequest {
    return UserBindRequestFromJSONTyped(json, false);
}

export function UserBindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBindRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'emailVerificationCode': json['emailVerificationCode'],
        'password': json['password'],
        'conformPassword': json['conformPassword'],
    };
}

export function UserBindRequestToJSON(value?: UserBindRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'emailVerificationCode': value.emailVerificationCode,
        'password': value.password,
        'conformPassword': value.conformPassword,
    };
}

