/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoGetRequest
 */
export interface UserInfoGetRequest {
    /**
     * 
     * @type {number}
     * @memberof UserInfoGetRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the UserInfoGetRequest interface.
 */
export function instanceOfUserInfoGetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInfoGetRequestFromJSON(json: any): UserInfoGetRequest {
    return UserInfoGetRequestFromJSONTyped(json, false);
}

export function UserInfoGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UserInfoGetRequestToJSON(value?: UserInfoGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

