/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegisterResponseAllOfData
 */
export interface UserRegisterResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterResponseAllOfData
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterResponseAllOfData
     */
    refreshToken?: string;
    /**
     * 
     * @type {number}
     * @memberof UserRegisterResponseAllOfData
     */
    id?: number;
}

/**
 * Check if a given object implements the UserRegisterResponseAllOfData interface.
 */
export function instanceOfUserRegisterResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRegisterResponseAllOfDataFromJSON(json: any): UserRegisterResponseAllOfData {
    return UserRegisterResponseAllOfDataFromJSONTyped(json, false);
}

export function UserRegisterResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UserRegisterResponseAllOfDataToJSON(value?: UserRegisterResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
        'id': value.id,
    };
}

