/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VerificationCodePurpose } from './VerificationCodePurpose';
import {
    VerificationCodePurposeFromJSON,
    VerificationCodePurposeFromJSONTyped,
    VerificationCodePurposeToJSON,
} from './VerificationCodePurpose';

/**
 * 
 * @export
 * @interface UserResetEmailRequest
 */
export interface UserResetEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof UserResetEmailRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserResetEmailRequest
     */
    emailVerificationCode: string;
    /**
     * 
     * @type {VerificationCodePurpose}
     * @memberof UserResetEmailRequest
     */
    purpose?: VerificationCodePurpose;
    /**
     * 
     * @type {number}
     * @memberof UserResetEmailRequest
     */
    executor?: number;
}

/**
 * Check if a given object implements the UserResetEmailRequest interface.
 */
export function instanceOfUserResetEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "emailVerificationCode" in value;

    return isInstance;
}

export function UserResetEmailRequestFromJSON(json: any): UserResetEmailRequest {
    return UserResetEmailRequestFromJSONTyped(json, false);
}

export function UserResetEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResetEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'emailVerificationCode': json['emailVerificationCode'],
        'purpose': !exists(json, 'purpose') ? undefined : VerificationCodePurposeFromJSON(json['purpose']),
        'executor': !exists(json, 'executor') ? undefined : json['executor'],
    };
}

export function UserResetEmailRequestToJSON(value?: UserResetEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'emailVerificationCode': value.emailVerificationCode,
        'purpose': VerificationCodePurposeToJSON(value.purpose),
        'executor': value.executor,
    };
}

