/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VerificationCodePurpose = {
    None: 'none',
    Register: 'register',
    Login: 'login',
    ResetPassword: 'resetPassword',
    ResetEmail: 'resetEmail'
} as const;
export type VerificationCodePurpose = typeof VerificationCodePurpose[keyof typeof VerificationCodePurpose];


export function VerificationCodePurposeFromJSON(json: any): VerificationCodePurpose {
    return VerificationCodePurposeFromJSONTyped(json, false);
}

export function VerificationCodePurposeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationCodePurpose {
    return json as VerificationCodePurpose;
}

export function VerificationCodePurposeToJSON(value?: VerificationCodePurpose | null): any {
    return value as any;
}

