/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthCaptchaGetRequest,
  AuthCaptchaGetResponse,
  AuthLoginRequest,
  AuthLoginResponse,
  AuthLogoutRequest,
  AuthLogoutResponse,
  AuthSendVerificationCodeRequest,
  AuthSendVerificationCodeResponse,
} from '../models/index';
import {
    AuthCaptchaGetRequestFromJSON,
    AuthCaptchaGetRequestToJSON,
    AuthCaptchaGetResponseFromJSON,
    AuthCaptchaGetResponseToJSON,
    AuthLoginRequestFromJSON,
    AuthLoginRequestToJSON,
    AuthLoginResponseFromJSON,
    AuthLoginResponseToJSON,
    AuthLogoutRequestFromJSON,
    AuthLogoutRequestToJSON,
    AuthLogoutResponseFromJSON,
    AuthLogoutResponseToJSON,
    AuthSendVerificationCodeRequestFromJSON,
    AuthSendVerificationCodeRequestToJSON,
    AuthSendVerificationCodeResponseFromJSON,
    AuthSendVerificationCodeResponseToJSON,
} from '../models/index';

export interface AuthCaptchaGetOperationRequest {
    authCaptchaGetRequest: AuthCaptchaGetRequest;
}

export interface AuthLoginOperationRequest {
    authLoginRequest: AuthLoginRequest;
}

export interface AuthLogoutOperationRequest {
    authLogoutRequest: AuthLogoutRequest;
}

export interface AuthSendVerificationCodeOperationRequest {
    authSendVerificationCodeRequest: AuthSendVerificationCodeRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authCaptchaGetRaw(requestParameters: AuthCaptchaGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthCaptchaGetResponse>> {
        if (requestParameters.authCaptchaGetRequest === null || requestParameters.authCaptchaGetRequest === undefined) {
            throw new runtime.RequiredError('authCaptchaGetRequest','Required parameter requestParameters.authCaptchaGetRequest was null or undefined when calling authCaptchaGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/captcha/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthCaptchaGetRequestToJSON(requestParameters.authCaptchaGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthCaptchaGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async authCaptchaGet(requestParameters: AuthCaptchaGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthCaptchaGetResponse> {
        const response = await this.authCaptchaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authLoginRaw(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginResponse>> {
        if (requestParameters.authLoginRequest === null || requestParameters.authLoginRequest === undefined) {
            throw new runtime.RequiredError('authLoginRequest','Required parameter requestParameters.authLoginRequest was null or undefined when calling authLogin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLoginRequestToJSON(requestParameters.authLoginRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginResponseFromJSON(jsonValue));
    }

    /**
     */
    async authLogin(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginResponse> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authLogoutRaw(requestParameters: AuthLogoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutResponse>> {
        if (requestParameters.authLogoutRequest === null || requestParameters.authLogoutRequest === undefined) {
            throw new runtime.RequiredError('authLogoutRequest','Required parameter requestParameters.authLogoutRequest was null or undefined when calling authLogout.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLogoutRequestToJSON(requestParameters.authLogoutRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async authLogout(requestParameters: AuthLogoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutResponse> {
        const response = await this.authLogoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authSendVerificationCodeRaw(requestParameters: AuthSendVerificationCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSendVerificationCodeResponse>> {
        if (requestParameters.authSendVerificationCodeRequest === null || requestParameters.authSendVerificationCodeRequest === undefined) {
            throw new runtime.RequiredError('authSendVerificationCodeRequest','Required parameter requestParameters.authSendVerificationCodeRequest was null or undefined when calling authSendVerificationCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/sendVerificationCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSendVerificationCodeRequestToJSON(requestParameters.authSendVerificationCodeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSendVerificationCodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async authSendVerificationCode(requestParameters: AuthSendVerificationCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSendVerificationCodeResponse> {
        const response = await this.authSendVerificationCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
