/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Token,
  TokenAddResponse,
} from '../models/index';
import {
    TokenFromJSON,
    TokenToJSON,
    TokenAddResponseFromJSON,
    TokenAddResponseToJSON,
} from '../models/index';

export interface TokenAddRequest {
    token: Token;
}

/**
 * 
 */
export class MessageApi extends runtime.BaseAPI {

    /**
     * 新增權杖
     */
    async tokenAddRaw(requestParameters: TokenAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenAddResponse>> {
        if (requestParameters.token === null || requestParameters.token === undefined) {
            throw new runtime.RequiredError('token','Required parameter requestParameters.token was null or undefined when calling tokenAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenToJSON(requestParameters.token),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增權杖
     */
    async tokenAdd(requestParameters: TokenAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenAddResponse> {
        const response = await this.tokenAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
