/* tslint:disable */
/* eslint-disable */
/**
 * user base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  User,
  UserBindRequest,
  UserBindResponse,
  UserForgetPasswordRequest,
  UserForgetPasswordResponse,
  UserGetByIdResponse,
  UserInfoGetRequest,
  UserInfoGetResponse,
  UserRegisterRequest,
  UserRegisterResponse,
  UserResetEmailRequest,
  UserResetEmailResponse,
  UserResetPasswordRequest,
  UserResetPasswordResponse,
} from '../models/index';
import {
    UserFromJSON,
    UserToJSON,
    UserBindRequestFromJSON,
    UserBindRequestToJSON,
    UserBindResponseFromJSON,
    UserBindResponseToJSON,
    UserForgetPasswordRequestFromJSON,
    UserForgetPasswordRequestToJSON,
    UserForgetPasswordResponseFromJSON,
    UserForgetPasswordResponseToJSON,
    UserGetByIdResponseFromJSON,
    UserGetByIdResponseToJSON,
    UserInfoGetRequestFromJSON,
    UserInfoGetRequestToJSON,
    UserInfoGetResponseFromJSON,
    UserInfoGetResponseToJSON,
    UserRegisterRequestFromJSON,
    UserRegisterRequestToJSON,
    UserRegisterResponseFromJSON,
    UserRegisterResponseToJSON,
    UserResetEmailRequestFromJSON,
    UserResetEmailRequestToJSON,
    UserResetEmailResponseFromJSON,
    UserResetEmailResponseToJSON,
    UserResetPasswordRequestFromJSON,
    UserResetPasswordRequestToJSON,
    UserResetPasswordResponseFromJSON,
    UserResetPasswordResponseToJSON,
} from '../models/index';

export interface UserBindOperationRequest {
    userId: number;
    userBindRequest: UserBindRequest;
}

export interface UserForgetPasswordOperationRequest {
    userForgetPasswordRequest: UserForgetPasswordRequest;
}

export interface UserGetByIdRequest {
    userId: number;
    user: User;
}

export interface UserInfoGetOperationRequest {
    userInfoGetRequest: UserInfoGetRequest;
}

export interface UserRegisterOperationRequest {
    userRegisterRequest: UserRegisterRequest;
}

export interface UserResetEmailOperationRequest {
    userId: string;
    userResetEmailRequest: UserResetEmailRequest;
}

export interface UserResetPasswordOperationRequest {
    userId: number;
    userResetPasswordRequest: UserResetPasswordRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     */
    async userBindRaw(requestParameters: UserBindOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserBindResponse>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling userBind.');
        }

        if (requestParameters.userBindRequest === null || requestParameters.userBindRequest === undefined) {
            throw new runtime.RequiredError('userBindRequest','Required parameter requestParameters.userBindRequest was null or undefined when calling userBind.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/{userId}/bind`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserBindRequestToJSON(requestParameters.userBindRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserBindResponseFromJSON(jsonValue));
    }

    /**
     */
    async userBind(requestParameters: UserBindOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserBindResponse> {
        const response = await this.userBindRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 用戶忘記密碼
     */
    async userForgetPasswordRaw(requestParameters: UserForgetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserForgetPasswordResponse>> {
        if (requestParameters.userForgetPasswordRequest === null || requestParameters.userForgetPasswordRequest === undefined) {
            throw new runtime.RequiredError('userForgetPasswordRequest','Required parameter requestParameters.userForgetPasswordRequest was null or undefined when calling userForgetPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/forgetPassword`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserForgetPasswordRequestToJSON(requestParameters.userForgetPasswordRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserForgetPasswordResponseFromJSON(jsonValue));
    }

    /**
     * 用戶忘記密碼
     */
    async userForgetPassword(requestParameters: UserForgetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserForgetPasswordResponse> {
        const response = await this.userForgetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得用戶資料
     */
    async userGetByIdRaw(requestParameters: UserGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGetByIdResponse>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling userGetById.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling userGetById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/{userId}/get`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters.user),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGetByIdResponseFromJSON(jsonValue));
    }

    /**
     * 取得用戶資料
     */
    async userGetById(requestParameters: UserGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGetByIdResponse> {
        const response = await this.userGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得用戶本身資料
     */
    async userInfoGetRaw(requestParameters: UserInfoGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfoGetResponse>> {
        if (requestParameters.userInfoGetRequest === null || requestParameters.userInfoGetRequest === undefined) {
            throw new runtime.RequiredError('userInfoGetRequest','Required parameter requestParameters.userInfoGetRequest was null or undefined when calling userInfoGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/info/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserInfoGetRequestToJSON(requestParameters.userInfoGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得用戶本身資料
     */
    async userInfoGet(requestParameters: UserInfoGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfoGetResponse> {
        const response = await this.userInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userRegisterRaw(requestParameters: UserRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRegisterResponse>> {
        if (requestParameters.userRegisterRequest === null || requestParameters.userRegisterRequest === undefined) {
            throw new runtime.RequiredError('userRegisterRequest','Required parameter requestParameters.userRegisterRequest was null or undefined when calling userRegister.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterRequestToJSON(requestParameters.userRegisterRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRegisterResponseFromJSON(jsonValue));
    }

    /**
     */
    async userRegister(requestParameters: UserRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRegisterResponse> {
        const response = await this.userRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 用戶重設email
     */
    async userResetEmailRaw(requestParameters: UserResetEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResetEmailResponse>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling userResetEmail.');
        }

        if (requestParameters.userResetEmailRequest === null || requestParameters.userResetEmailRequest === undefined) {
            throw new runtime.RequiredError('userResetEmailRequest','Required parameter requestParameters.userResetEmailRequest was null or undefined when calling userResetEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/{userId}/resetEmail`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserResetEmailRequestToJSON(requestParameters.userResetEmailRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResetEmailResponseFromJSON(jsonValue));
    }

    /**
     * 用戶重設email
     */
    async userResetEmail(requestParameters: UserResetEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResetEmailResponse> {
        const response = await this.userResetEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 用戶重設密碼
     */
    async userResetPasswordRaw(requestParameters: UserResetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResetPasswordResponse>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling userResetPassword.');
        }

        if (requestParameters.userResetPasswordRequest === null || requestParameters.userResetPasswordRequest === undefined) {
            throw new runtime.RequiredError('userResetPasswordRequest','Required parameter requestParameters.userResetPasswordRequest was null or undefined when calling userResetPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/{userId}/resetPassword`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserResetPasswordRequestToJSON(requestParameters.userResetPasswordRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResetPasswordResponseFromJSON(jsonValue));
    }

    /**
     * 用戶重設密碼
     */
    async userResetPassword(requestParameters: UserResetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResetPasswordResponse> {
        const response = await this.userResetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
