/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmailSendRequest,
  EmailSendResponse,
  EmailSendWithTemplateRequest,
  EmailSendWithTemplateResponse,
} from '../models/index';
import {
    EmailSendRequestFromJSON,
    EmailSendRequestToJSON,
    EmailSendResponseFromJSON,
    EmailSendResponseToJSON,
    EmailSendWithTemplateRequestFromJSON,
    EmailSendWithTemplateRequestToJSON,
    EmailSendWithTemplateResponseFromJSON,
    EmailSendWithTemplateResponseToJSON,
} from '../models/index';

export interface EmailSendOperationRequest {
    emailSendRequest: EmailSendRequest;
}

export interface EmailSendWithTemplateOperationRequest {
    emailSendWithTemplateRequest: EmailSendWithTemplateRequest;
}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI {

    /**
     */
    async emailSendRaw(requestParameters: EmailSendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailSendResponse>> {
        if (requestParameters.emailSendRequest === null || requestParameters.emailSendRequest === undefined) {
            throw new runtime.RequiredError('emailSendRequest','Required parameter requestParameters.emailSendRequest was null or undefined when calling emailSend.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/email/send`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailSendRequestToJSON(requestParameters.emailSendRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailSendResponseFromJSON(jsonValue));
    }

    /**
     */
    async emailSend(requestParameters: EmailSendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailSendResponse> {
        const response = await this.emailSendRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async emailSendWithTemplateRaw(requestParameters: EmailSendWithTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailSendWithTemplateResponse>> {
        if (requestParameters.emailSendWithTemplateRequest === null || requestParameters.emailSendWithTemplateRequest === undefined) {
            throw new runtime.RequiredError('emailSendWithTemplateRequest','Required parameter requestParameters.emailSendWithTemplateRequest was null or undefined when calling emailSendWithTemplate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/email/sendWithTemplate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailSendWithTemplateRequestToJSON(requestParameters.emailSendWithTemplateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailSendWithTemplateResponseFromJSON(jsonValue));
    }

    /**
     */
    async emailSendWithTemplate(requestParameters: EmailSendWithTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailSendWithTemplateResponse> {
        const response = await this.emailSendWithTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
