/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Message,
  MessageAddResponse,
  MessageGetByIdResponse,
} from '../models/index';
import {
    MessageFromJSON,
    MessageToJSON,
    MessageAddResponseFromJSON,
    MessageAddResponseToJSON,
    MessageGetByIdResponseFromJSON,
    MessageGetByIdResponseToJSON,
} from '../models/index';

export interface MessageAddRequest {
    message: Message;
}

export interface MessageGetByIdRequest {
    messageId: number;
}

/**
 * 
 */
export class MessageApi extends runtime.BaseAPI {

    /**
     * 新增訊息
     */
    async messageAddRaw(requestParameters: MessageAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageAddResponse>> {
        if (requestParameters.message === null || requestParameters.message === undefined) {
            throw new runtime.RequiredError('message','Required parameter requestParameters.message was null or undefined when calling messageAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/message`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageToJSON(requestParameters.message),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增訊息
     */
    async messageAdd(requestParameters: MessageAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageAddResponse> {
        const response = await this.messageAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得通知紀錄
     */
    async messageGetByIdRaw(requestParameters: MessageGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageGetByIdResponse>> {
        if (requestParameters.messageId === null || requestParameters.messageId === undefined) {
            throw new runtime.RequiredError('messageId','Required parameter requestParameters.messageId was null or undefined when calling messageGetById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/message/{messageId}`.replace(`{${"messageId"}}`, encodeURIComponent(String(requestParameters.messageId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageGetByIdResponseFromJSON(jsonValue));
    }

    /**
     * 取得通知紀錄
     */
    async messageGetById(requestParameters: MessageGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageGetByIdResponse> {
        const response = await this.messageGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
