/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Passageway,
  PassagewayGetResponse,
} from '../models/index';
import {
    PassagewayFromJSON,
    PassagewayToJSON,
    PassagewayGetResponseFromJSON,
    PassagewayGetResponseToJSON,
} from '../models/index';

export interface PassagewayGetRequest {
    passageway: Passageway;
}

/**
 * 
 */
export class PassagewayApi extends runtime.BaseAPI {

    /**
     * 取得頻道
     */
    async passagewayGetRaw(requestParameters: PassagewayGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PassagewayGetResponse>> {
        if (requestParameters.passageway === null || requestParameters.passageway === undefined) {
            throw new runtime.RequiredError('passageway','Required parameter requestParameters.passageway was null or undefined when calling passagewayGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/passageway`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: PassagewayToJSON(requestParameters.passageway),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PassagewayGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得頻道
     */
    async passagewayGet(requestParameters: PassagewayGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PassagewayGetResponse> {
        const response = await this.passagewayGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
