/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SendRecord,
  SendRecordAddResponse,
  SendRecordGetByIdResponse,
} from '../models/index';
import {
    SendRecordFromJSON,
    SendRecordToJSON,
    SendRecordAddResponseFromJSON,
    SendRecordAddResponseToJSON,
    SendRecordGetByIdResponseFromJSON,
    SendRecordGetByIdResponseToJSON,
} from '../models/index';

export interface SendRecordAddRequest {
    sendRecord: SendRecord;
}

export interface SendRecordGetByIdRequest {
    sendRecordId: number;
}

/**
 * 
 */
export class SendRecordApi extends runtime.BaseAPI {

    /**
     * 新增傳送紀錄
     */
    async sendRecordAddRaw(requestParameters: SendRecordAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendRecordAddResponse>> {
        if (requestParameters.sendRecord === null || requestParameters.sendRecord === undefined) {
            throw new runtime.RequiredError('sendRecord','Required parameter requestParameters.sendRecord was null or undefined when calling sendRecordAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sendRecord`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendRecordToJSON(requestParameters.sendRecord),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendRecordAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增傳送紀錄
     */
    async sendRecordAdd(requestParameters: SendRecordAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendRecordAddResponse> {
        const response = await this.sendRecordAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得通知紀錄
     */
    async sendRecordGetByIdRaw(requestParameters: SendRecordGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendRecordGetByIdResponse>> {
        if (requestParameters.sendRecordId === null || requestParameters.sendRecordId === undefined) {
            throw new runtime.RequiredError('sendRecordId','Required parameter requestParameters.sendRecordId was null or undefined when calling sendRecordGetById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sendRecord/{sendRecordId}`.replace(`{${"sendRecordId"}}`, encodeURIComponent(String(requestParameters.sendRecordId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendRecordGetByIdResponseFromJSON(jsonValue));
    }

    /**
     * 取得通知紀錄
     */
    async sendRecordGetById(requestParameters: SendRecordGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendRecordGetByIdResponse> {
        const response = await this.sendRecordGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
