/* tslint:disable */
/* eslint-disable */
/**
 * notify base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TemplateAddRequest,
  TemplateAddResponse,
  TemplateGetByIdResponse,
  TemplateGetRequest,
  TemplateGetResponse,
  TemplateUpdateRequest,
  TemplateUpdateResponse,
} from '../models/index';
import {
    TemplateAddRequestFromJSON,
    TemplateAddRequestToJSON,
    TemplateAddResponseFromJSON,
    TemplateAddResponseToJSON,
    TemplateGetByIdResponseFromJSON,
    TemplateGetByIdResponseToJSON,
    TemplateGetRequestFromJSON,
    TemplateGetRequestToJSON,
    TemplateGetResponseFromJSON,
    TemplateGetResponseToJSON,
    TemplateUpdateRequestFromJSON,
    TemplateUpdateRequestToJSON,
    TemplateUpdateResponseFromJSON,
    TemplateUpdateResponseToJSON,
} from '../models/index';

export interface TemplateAddOperationRequest {
    templateAddRequest: TemplateAddRequest;
}

export interface TemplateGetOperationRequest {
    templateGetRequest: TemplateGetRequest;
}

export interface TemplateGetByIdRequest {
    templateId: number;
}

export interface TemplateUpdateOperationRequest {
    templateUpdateRequest: TemplateUpdateRequest;
}

/**
 * 
 */
export class TemplateApi extends runtime.BaseAPI {

    /**
     * 新增樣板
     */
    async templateAddRaw(requestParameters: TemplateAddOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateAddResponse>> {
        if (requestParameters.templateAddRequest === null || requestParameters.templateAddRequest === undefined) {
            throw new runtime.RequiredError('templateAddRequest','Required parameter requestParameters.templateAddRequest was null or undefined when calling templateAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/template`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateAddRequestToJSON(requestParameters.templateAddRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增樣板
     */
    async templateAdd(requestParameters: TemplateAddOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateAddResponse> {
        const response = await this.templateAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得通知樣板
     */
    async templateGetRaw(requestParameters: TemplateGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateGetResponse>> {
        if (requestParameters.templateGetRequest === null || requestParameters.templateGetRequest === undefined) {
            throw new runtime.RequiredError('templateGetRequest','Required parameter requestParameters.templateGetRequest was null or undefined when calling templateGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/template`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateGetRequestToJSON(requestParameters.templateGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得通知樣板
     */
    async templateGet(requestParameters: TemplateGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateGetResponse> {
        const response = await this.templateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得通知樣板
     */
    async templateGetByIdRaw(requestParameters: TemplateGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateGetByIdResponse>> {
        if (requestParameters.templateId === null || requestParameters.templateId === undefined) {
            throw new runtime.RequiredError('templateId','Required parameter requestParameters.templateId was null or undefined when calling templateGetById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/template/{templateId}`.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters.templateId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateGetByIdResponseFromJSON(jsonValue));
    }

    /**
     * 取得通知樣板
     */
    async templateGetById(requestParameters: TemplateGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateGetByIdResponse> {
        const response = await this.templateGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async templateUpdateRaw(requestParameters: TemplateUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateUpdateResponse>> {
        if (requestParameters.templateUpdateRequest === null || requestParameters.templateUpdateRequest === undefined) {
            throw new runtime.RequiredError('templateUpdateRequest','Required parameter requestParameters.templateUpdateRequest was null or undefined when calling templateUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/template`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateUpdateRequestToJSON(requestParameters.templateUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async templateUpdate(requestParameters: TemplateUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateUpdateResponse> {
        const response = await this.templateUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
