/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type AgencyAPI interface {


    // AgencyAdd Post /agency
     AgencyAdd(c *gin.Context)

    // AgencyBatchUpdate Patch /agency
     AgencyBatchUpdate(c *gin.Context)

    // AgencyGet Post /agencyGet
     AgencyGet(c *gin.Context)

    // AgencyPageGet Post /agency/pageGet
     AgencyPageGet(c *gin.Context)

    // AgencyUpdate Patch /agency/:agencyId
     AgencyUpdate(c *gin.Context)

}