/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PhoneNumber struct {

	CountryCode int32 `json:"countryCode,omitempty"`

	NationalPhoneNumber string `json:"nationalPhoneNumber,omitempty"`
}
