/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Platform struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	// 1:phone 2:email 3:username
	RegistrationMethod int32 `json:"registrationMethod,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
