/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type AgencyWithPlanPageRequest struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	CountryCode int32 `json:"countryCode,omitempty"`

	NationalPhoneNumber string `json:"nationalPhoneNumber,omitempty"`

	// 1:active 2:inactive
	AgencyStatus int32 `json:"agencyStatus,omitempty"`

	PlatformId int64 `json:"platformId,omitempty"`

	PlatformName string `json:"platformName,omitempty"`

	// 1:phone 2:email 3:username
	RegistrationMethod int32 `json:"registrationMethod,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	PlanId int64 `json:"planId,omitempty"`

	PlanName string `json:"planName,omitempty"`

	// 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation int32 `json:"cardAssociation,omitempty"`

	// in percentage
	Discount float32 `json:"discount,omitempty"`

	ReferralCode string `json:"referralCode,omitempty"`

	// 1:active 2:inactive
	PlanStatus int32 `json:"planStatus,omitempty"`

	CreatedAtFrom time.Time `json:"createdAtFrom,omitempty"`

	CreatedAtTo time.Time `json:"createdAtTo,omitempty"`

	UpdatedAtFrom time.Time `json:"updatedAtFrom,omitempty"`

	UpdatedAtTo time.Time `json:"updatedAtTo,omitempty"`

	OrderByColumn string `json:"orderByColumn,omitempty"`

	// 1:asc 2:desc
	OrderByDirection int32 `json:"orderByDirection,omitempty"`

	// 1:newest 2:oldest 3:newest active 4:oldest active
	Strategy int32 `json:"strategy,omitempty"`

	PageCurrent int32 `json:"pageCurrent,omitempty"`

	PageSize int32 `json:"pageSize,omitempty"`
}
