/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AgencyWithPlanAddResponseAllOfData struct {

	AgencyId int64 `json:"agencyId,omitempty"`

	AgencyPlanId int64 `json:"agencyPlanId,omitempty"`
}
