/*
 * agency base
 *
 * This is my API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Agency struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	CountryCode int32 `json:"countryCode,omitempty"`

	NationalPhoneNumber string `json:"nationalPhoneNumber,omitempty"`

	// 1:active 2:inactive
	AgencyStatus int32 `json:"agencyStatus,omitempty"`

	PlatformId int64 `json:"platformId,omitempty"`

	PlatformName string `json:"platformName,omitempty"`

	// 1:phone 2:email 3:username
	RegistrationMethod int32 `json:"registrationMethod,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
