product:
  type: object
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    storeId:
      type: integer
      format: int64
    price:
      type: number
      description: product price
    quantity:
      type: integer
    currency:
      type: string
    remark:
      type: string
    productDescriptionId:
      type: integer
      format: int64
    introduction:
      type: string
    applicationInstructions:
      type: string
    feeSchedule:
      type: string
    agreement:
      type: string
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    description:
      "$ref": "../schemas.yml#/schemas/productDescription"
    isApplied:
      type: boolean

    