/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CardAssociation = {
    None: 'none',
    Visa: 'visa',
    MasterCard: 'masterCard',
    AmericanExpress: 'AmericanExpress',
    Jcb: 'JCB',
    UnionPay: 'unionPay'
} as const;
export type CardAssociation = typeof CardAssociation[keyof typeof CardAssociation];


export function CardAssociationFromJSON(json: any): CardAssociation {
    return CardAssociationFromJSONTyped(json, false);
}

export function CardAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardAssociation {
    return json as CardAssociation;
}

export function CardAssociationToJSON(value?: CardAssociation | null): any {
    return value as any;
}

