/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardProduct
 */
export interface CardProduct {
    /**
     * 
     * @type {number}
     * @memberof CardProduct
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CardProduct
     */
    name?: string;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {number}
     * @memberof CardProduct
     */
    cardAssociation?: number;
    /**
     * 
     * @type {number}
     * @memberof CardProduct
     */
    cardIssuerId?: number;
    /**
     * 
     * @type {string}
     * @memberof CardProduct
     */
    cardIssuerName?: string;
    /**
     * card limit
     * @type {number}
     * @memberof CardProduct
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof CardProduct
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof CardProduct
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof CardProduct
     */
    remark?: string;
    /**
     * 
     * @type {Date}
     * @memberof CardProduct
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardProduct
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CardProduct interface.
 */
export function instanceOfCardProduct(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardProductFromJSON(json: any): CardProduct {
    return CardProductFromJSONTyped(json, false);
}

export function CardProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'cardIssuerId': !exists(json, 'cardIssuerId') ? undefined : json['cardIssuerId'],
        'cardIssuerName': !exists(json, 'cardIssuerName') ? undefined : json['cardIssuerName'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function CardProductToJSON(value?: CardProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'cardAssociation': value.cardAssociation,
        'cardIssuerId': value.cardIssuerId,
        'cardIssuerName': value.cardIssuerName,
        'balance': value.balance,
        'cryptocurrency': value.cryptocurrency,
        'currency': value.currency,
        'remark': value.remark,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

