/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardIssuer } from './CardIssuer';
import {
    CardIssuerFromJSON,
    CardIssuerFromJSONTyped,
    CardIssuerToJSON,
} from './CardIssuer';

/**
 * 
 * @export
 * @interface CardIssuerGetResponse
 */
export interface CardIssuerGetResponse {
    /**
     * 
     * @type {number}
     * @memberof CardIssuerGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CardIssuerGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CardIssuerGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardIssuerGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<CardIssuer>}
     * @memberof CardIssuerGetResponse
     */
    data?: Array<CardIssuer>;
}

/**
 * Check if a given object implements the CardIssuerGetResponse interface.
 */
export function instanceOfCardIssuerGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardIssuerGetResponseFromJSON(json: any): CardIssuerGetResponse {
    return CardIssuerGetResponseFromJSONTyped(json, false);
}

export function CardIssuerGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardIssuerGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CardIssuerFromJSON)),
    };
}

export function CardIssuerGetResponseToJSON(value?: CardIssuerGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CardIssuerToJSON)),
    };
}

