/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CardProduct } from './CardProduct';
import {
    CardProductFromJSON,
    CardProductFromJSONTyped,
    CardProductToJSON,
} from './CardProduct';

/**
 * 
 * @export
 * @interface CardProductGetResponse
 */
export interface CardProductGetResponse {
    /**
     * 
     * @type {number}
     * @memberof CardProductGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CardProductGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CardProductGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardProductGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<CardProduct>}
     * @memberof CardProductGetResponse
     */
    data?: Array<CardProduct>;
}

/**
 * Check if a given object implements the CardProductGetResponse interface.
 */
export function instanceOfCardProductGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardProductGetResponseFromJSON(json: any): CardProductGetResponse {
    return CardProductGetResponseFromJSONTyped(json, false);
}

export function CardProductGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardProductGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CardProductFromJSON)),
    };
}

export function CardProductGetResponseToJSON(value?: CardProductGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CardProductToJSON)),
    };
}

