/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardIssuer
 */
export interface CardIssuer {
    /**
     * 
     * @type {number}
     * @memberof CardIssuer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CardIssuer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CardIssuer
     */
    remark?: string;
    /**
     * 
     * @type {Date}
     * @memberof CardIssuer
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardIssuer
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CardIssuer interface.
 */
export function instanceOfCardIssuer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardIssuerFromJSON(json: any): CardIssuer {
    return CardIssuerFromJSONTyped(json, false);
}

export function CardIssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardIssuer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function CardIssuerToJSON(value?: CardIssuer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'remark': value.remark,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

