/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDisplayAllResponseAllOfProductsByCardAssociation } from './ProductDisplayAllResponseAllOfProductsByCardAssociation';
import {
    ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSON,
    ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSONTyped,
    ProductDisplayAllResponseAllOfProductsByCardAssociationToJSON,
} from './ProductDisplayAllResponseAllOfProductsByCardAssociation';

/**
 * 
 * @export
 * @interface ProductDisplayAllResponseAllOfData
 */
export interface ProductDisplayAllResponseAllOfData {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayAllResponseAllOfData
     */
    cardIssuerId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDisplayAllResponseAllOfData
     */
    cardIssuerName?: string;
    /**
     * 
     * @type {Array<ProductDisplayAllResponseAllOfProductsByCardAssociation>}
     * @memberof ProductDisplayAllResponseAllOfData
     */
    productsByCardAssociation?: Array<ProductDisplayAllResponseAllOfProductsByCardAssociation>;
}

/**
 * Check if a given object implements the ProductDisplayAllResponseAllOfData interface.
 */
export function instanceOfProductDisplayAllResponseAllOfData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayAllResponseAllOfDataFromJSON(json: any): ProductDisplayAllResponseAllOfData {
    return ProductDisplayAllResponseAllOfDataFromJSONTyped(json, false);
}

export function ProductDisplayAllResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayAllResponseAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardIssuerId': !exists(json, 'cardIssuerId') ? undefined : json['cardIssuerId'],
        'cardIssuerName': !exists(json, 'cardIssuerName') ? undefined : json['cardIssuerName'],
        'productsByCardAssociation': !exists(json, 'productsByCardAssociation') ? undefined : ((json['productsByCardAssociation'] as Array<any>).map(ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSON)),
    };
}

export function ProductDisplayAllResponseAllOfDataToJSON(value?: ProductDisplayAllResponseAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cardIssuerId': value.cardIssuerId,
        'cardIssuerName': value.cardIssuerName,
        'productsByCardAssociation': value.productsByCardAssociation === undefined ? undefined : ((value.productsByCardAssociation as Array<any>).map(ProductDisplayAllResponseAllOfProductsByCardAssociationToJSON)),
    };
}

