/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDisplayAllResponseAllOfData } from './ProductDisplayAllResponseAllOfData';
import {
    ProductDisplayAllResponseAllOfDataFromJSON,
    ProductDisplayAllResponseAllOfDataFromJSONTyped,
    ProductDisplayAllResponseAllOfDataToJSON,
} from './ProductDisplayAllResponseAllOfData';

/**
 * 
 * @export
 * @interface ProductDisplayAllResponse
 */
export interface ProductDisplayAllResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayAllResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDisplayAllResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDisplayAllResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDisplayAllResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ProductDisplayAllResponseAllOfData>}
     * @memberof ProductDisplayAllResponse
     */
    data?: Array<ProductDisplayAllResponseAllOfData>;
}

/**
 * Check if a given object implements the ProductDisplayAllResponse interface.
 */
export function instanceOfProductDisplayAllResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayAllResponseFromJSON(json: any): ProductDisplayAllResponse {
    return ProductDisplayAllResponseFromJSONTyped(json, false);
}

export function ProductDisplayAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayAllResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ProductDisplayAllResponseAllOfDataFromJSON)),
    };
}

export function ProductDisplayAllResponseToJSON(value?: ProductDisplayAllResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ProductDisplayAllResponseAllOfDataToJSON)),
    };
}

