/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDescription
 */
export interface ProductDescription {
    /**
     * 
     * @type {number}
     * @memberof ProductDescription
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    name?: string;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {number}
     * @memberof ProductDescription
     */
    cardAssociation?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDescription
     */
    cardProductId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    introduction?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    applicationInstructions?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    feeSchedule?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    agreement?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescription
     */
    remark?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductDescription
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductDescription
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ProductDescription interface.
 */
export function instanceOfProductDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDescriptionFromJSON(json: any): ProductDescription {
    return ProductDescriptionFromJSONTyped(json, false);
}

export function ProductDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'cardProductId': !exists(json, 'cardProductId') ? undefined : json['cardProductId'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'introduction': !exists(json, 'introduction') ? undefined : json['introduction'],
        'applicationInstructions': !exists(json, 'applicationInstructions') ? undefined : json['applicationInstructions'],
        'feeSchedule': !exists(json, 'feeSchedule') ? undefined : json['feeSchedule'],
        'agreement': !exists(json, 'agreement') ? undefined : json['agreement'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ProductDescriptionToJSON(value?: ProductDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'cardAssociation': value.cardAssociation,
        'cardProductId': value.cardProductId,
        'cryptocurrency': value.cryptocurrency,
        'currency': value.currency,
        'introduction': value.introduction,
        'applicationInstructions': value.applicationInstructions,
        'feeSchedule': value.feeSchedule,
        'agreement': value.agreement,
        'remark': value.remark,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

