/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDescription } from './ProductDescription';
import {
    ProductDescriptionFromJSON,
    ProductDescriptionFromJSONTyped,
    ProductDescriptionToJSON,
} from './ProductDescription';

/**
 * 
 * @export
 * @interface ProductDescriptionGetResponse
 */
export interface ProductDescriptionGetResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductDescriptionGetResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDescriptionGetResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescriptionGetResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDescriptionGetResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ProductDescription>}
     * @memberof ProductDescriptionGetResponse
     */
    data?: Array<ProductDescription>;
}

/**
 * Check if a given object implements the ProductDescriptionGetResponse interface.
 */
export function instanceOfProductDescriptionGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDescriptionGetResponseFromJSON(json: any): ProductDescriptionGetResponse {
    return ProductDescriptionGetResponseFromJSONTyped(json, false);
}

export function ProductDescriptionGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDescriptionGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ProductDescriptionFromJSON)),
    };
}

export function ProductDescriptionGetResponseToJSON(value?: ProductDescriptionGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ProductDescriptionToJSON)),
    };
}

