/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductDisplayAllResponseAllOfProductsByCardAssociation
 */
export interface ProductDisplayAllResponseAllOfProductsByCardAssociation {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayAllResponseAllOfProductsByCardAssociation
     */
    cardAssociation?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayAllResponseAllOfProductsByCardAssociation
     */
    cardAssociationName?: number;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductDisplayAllResponseAllOfProductsByCardAssociation
     */
    products?: Array<Product>;
}

/**
 * Check if a given object implements the ProductDisplayAllResponseAllOfProductsByCardAssociation interface.
 */
export function instanceOfProductDisplayAllResponseAllOfProductsByCardAssociation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSON(json: any): ProductDisplayAllResponseAllOfProductsByCardAssociation {
    return ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSONTyped(json, false);
}

export function ProductDisplayAllResponseAllOfProductsByCardAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayAllResponseAllOfProductsByCardAssociation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'cardAssociationName': !exists(json, 'cardAssociationName') ? undefined : json['cardAssociationName'],
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductDisplayAllResponseAllOfProductsByCardAssociationToJSON(value?: ProductDisplayAllResponseAllOfProductsByCardAssociation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cardAssociation': value.cardAssociation,
        'cardAssociationName': value.cardAssociationName,
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(ProductToJSON)),
    };
}

