/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDescription } from './ProductDescription';
import {
    ProductDescriptionFromJSON,
    ProductDescriptionFromJSONTyped,
    ProductDescriptionToJSON,
} from './ProductDescription';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name?: string;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {number}
     * @memberof Product
     */
    cardAssociation?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    cardIssuerId?: number;
    /**
     * card limit
     * @type {number}
     * @memberof Product
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    cryptocurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    remark?: string;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    updatedAt?: Date;
    /**
     * 
     * @type {ProductDescription}
     * @memberof Product
     */
    description?: ProductDescription;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    isApplied?: boolean;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
        'cardIssuerId': !exists(json, 'cardIssuerId') ? undefined : json['cardIssuerId'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : json['cryptocurrency'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'remark': !exists(json, 'remark') ? undefined : json['remark'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'description': !exists(json, 'description') ? undefined : ProductDescriptionFromJSON(json['description']),
        'isApplied': !exists(json, 'isApplied') ? undefined : json['isApplied'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'cardAssociation': value.cardAssociation,
        'cardIssuerId': value.cardIssuerId,
        'balance': value.balance,
        'cryptocurrency': value.cryptocurrency,
        'currency': value.currency,
        'remark': value.remark,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'description': ProductDescriptionToJSON(value.description),
        'isApplied': value.isApplied,
    };
}

