/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDisplayRequest
 */
export interface ProductDisplayRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayRequest
     */
    userId?: number;
    /**
     * 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
     * @type {string}
     * @memberof ProductDisplayRequest
     */
    cardAssociation?: string;
}

/**
 * Check if a given object implements the ProductDisplayRequest interface.
 */
export function instanceOfProductDisplayRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayRequestFromJSON(json: any): ProductDisplayRequest {
    return ProductDisplayRequestFromJSONTyped(json, false);
}

export function ProductDisplayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'cardAssociation': !exists(json, 'cardAssociation') ? undefined : json['cardAssociation'],
    };
}

export function ProductDisplayRequestToJSON(value?: ProductDisplayRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'cardAssociation': value.cardAssociation,
    };
}

