/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductDisplayAllRequest
 */
export interface ProductDisplayAllRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayAllRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the ProductDisplayAllRequest interface.
 */
export function instanceOfProductDisplayAllRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayAllRequestFromJSON(json: any): ProductDisplayAllRequest {
    return ProductDisplayAllRequestFromJSONTyped(json, false);
}

export function ProductDisplayAllRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayAllRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function ProductDisplayAllRequestToJSON(value?: ProductDisplayAllRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

