/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductDisplayResponse
 */
export interface ProductDisplayResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductDisplayResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDisplayResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDisplayResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDisplayResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductDisplayResponse
     */
    data?: Array<Product>;
}

/**
 * Check if a given object implements the ProductDisplayResponse interface.
 */
export function instanceOfProductDisplayResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDisplayResponseFromJSON(json: any): ProductDisplayResponse {
    return ProductDisplayResponseFromJSONTyped(json, false);
}

export function ProductDisplayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDisplayResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductDisplayResponseToJSON(value?: ProductDisplayResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ProductToJSON)),
    };
}

