/* tslint:disable */
/* eslint-disable */
/**
 * card base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDescription } from './ProductDescription';
import {
    ProductDescriptionFromJSON,
    ProductDescriptionFromJSONTyped,
    ProductDescriptionToJSON,
} from './ProductDescription';

/**
 * 
 * @export
 * @interface ProductDescriptionUpdateResponse
 */
export interface ProductDescriptionUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductDescriptionUpdateResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDescriptionUpdateResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDescriptionUpdateResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDescriptionUpdateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ProductDescription}
     * @memberof ProductDescriptionUpdateResponse
     */
    data?: ProductDescription;
}

/**
 * Check if a given object implements the ProductDescriptionUpdateResponse interface.
 */
export function instanceOfProductDescriptionUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductDescriptionUpdateResponseFromJSON(json: any): ProductDescriptionUpdateResponse {
    return ProductDescriptionUpdateResponseFromJSONTyped(json, false);
}

export function ProductDescriptionUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDescriptionUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'data': !exists(json, 'data') ? undefined : ProductDescriptionFromJSON(json['data']),
    };
}

export function ProductDescriptionUpdateResponseToJSON(value?: ProductDescriptionUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'requestId': value.requestId,
        'success': value.success,
        'data': ProductDescriptionToJSON(value.data),
    };
}

