---
productDisplayAllResponse:
  allOf:
    - $ref: "../../schemas.yml#/schemas/result"
    - type: object
      properties:
        data:
          type: array
          items: 
            type: object
            properties:
              storeId:
                type: integer
                format: int64
              storeName:
                type: string
              productsByStore:
                type: array
                items: 
                  type: object
                  properties:
                    storeId:
                      type: integer
                      format: int64
                    storeName:
                      type: string
                    products:
                      type: array
                      items: 
                        "$ref": "../../schemas.yml#/schemas/product"


    