/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CardOrder,
  CardOrderAddResponse,
  CardOrderApplyRequest,
  CardOrderApplyResponse,
  CardOrderCancelResponse,
  CardOrderGetResponse,
  CardOrderLatestExpiredGetRequest,
  CardOrderLatestExpiredGetResponse,
  CardOrderPageRequest,
  CardOrderPageResponse,
  CardOrderRepayRequest,
  CardOrderRepayResponse,
  CardOrderUpdateResponse,
} from '../models/index';
import {
    CardOrderFromJSON,
    CardOrderToJSON,
    CardOrderAddResponseFromJSON,
    CardOrderAddResponseToJSON,
    CardOrderApplyRequestFromJSON,
    CardOrderApplyRequestToJSON,
    CardOrderApplyResponseFromJSON,
    CardOrderApplyResponseToJSON,
    CardOrderCancelResponseFromJSON,
    CardOrderCancelResponseToJSON,
    CardOrderGetResponseFromJSON,
    CardOrderGetResponseToJSON,
    CardOrderLatestExpiredGetRequestFromJSON,
    CardOrderLatestExpiredGetRequestToJSON,
    CardOrderLatestExpiredGetResponseFromJSON,
    CardOrderLatestExpiredGetResponseToJSON,
    CardOrderPageRequestFromJSON,
    CardOrderPageRequestToJSON,
    CardOrderPageResponseFromJSON,
    CardOrderPageResponseToJSON,
    CardOrderRepayRequestFromJSON,
    CardOrderRepayRequestToJSON,
    CardOrderRepayResponseFromJSON,
    CardOrderRepayResponseToJSON,
    CardOrderUpdateResponseFromJSON,
    CardOrderUpdateResponseToJSON,
} from '../models/index';

export interface CardOrderAddRequest {
    cardOrder: CardOrder;
}

export interface CardOrderApplyOperationRequest {
    cardOrderApplyRequest: CardOrderApplyRequest;
}

export interface CardOrderCancelRequest {
    cardOrderId: number;
}

export interface CardOrderGetRequest {
    cardOrder: CardOrder;
}

export interface CardOrderLatestExpiredGetOperationRequest {
    cardOrderLatestExpiredGetRequest: CardOrderLatestExpiredGetRequest;
}

export interface CardOrderPageOperationRequest {
    cardOrderPageRequest: CardOrderPageRequest;
}

export interface CardOrderRepayOperationRequest {
    cardOrderId: number;
    cardOrderRepayRequest: CardOrderRepayRequest;
}

export interface CardOrderUpdateRequest {
    cardOrderId: number;
    cardOrder: CardOrder;
}

/**
 * 
 */
export class CardOrderApi extends runtime.BaseAPI {

    /**
     * 新增卡片訂單
     */
    async cardOrderAddRaw(requestParameters: CardOrderAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderAddResponse>> {
        if (requestParameters.cardOrder === null || requestParameters.cardOrder === undefined) {
            throw new runtime.RequiredError('cardOrder','Required parameter requestParameters.cardOrder was null or undefined when calling cardOrderAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderToJSON(requestParameters.cardOrder),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增卡片訂單
     */
    async cardOrderAdd(requestParameters: CardOrderAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderAddResponse> {
        const response = await this.cardOrderAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 申請卡片訂單
     */
    async cardOrderApplyRaw(requestParameters: CardOrderApplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderApplyResponse>> {
        if (requestParameters.cardOrderApplyRequest === null || requestParameters.cardOrderApplyRequest === undefined) {
            throw new runtime.RequiredError('cardOrderApplyRequest','Required parameter requestParameters.cardOrderApplyRequest was null or undefined when calling cardOrderApply.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/apply`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderApplyRequestToJSON(requestParameters.cardOrderApplyRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderApplyResponseFromJSON(jsonValue));
    }

    /**
     * 申請卡片訂單
     */
    async cardOrderApply(requestParameters: CardOrderApplyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderApplyResponse> {
        const response = await this.cardOrderApplyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取消卡片訂單
     */
    async cardOrderCancelRaw(requestParameters: CardOrderCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderCancelResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderCancel.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}/cancel`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderCancelResponseFromJSON(jsonValue));
    }

    /**
     * 取消卡片訂單
     */
    async cardOrderCancel(requestParameters: CardOrderCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderCancelResponse> {
        const response = await this.cardOrderCancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得卡片訂單
     */
    async cardOrderGetRaw(requestParameters: CardOrderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderGetResponse>> {
        if (requestParameters.cardOrder === null || requestParameters.cardOrder === undefined) {
            throw new runtime.RequiredError('cardOrder','Required parameter requestParameters.cardOrder was null or undefined when calling cardOrderGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderToJSON(requestParameters.cardOrder),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得卡片訂單
     */
    async cardOrderGet(requestParameters: CardOrderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderGetResponse> {
        const response = await this.cardOrderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得最新超時卡片訂單
     */
    async cardOrderLatestExpiredGetRaw(requestParameters: CardOrderLatestExpiredGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderLatestExpiredGetResponse>> {
        if (requestParameters.cardOrderLatestExpiredGetRequest === null || requestParameters.cardOrderLatestExpiredGetRequest === undefined) {
            throw new runtime.RequiredError('cardOrderLatestExpiredGetRequest','Required parameter requestParameters.cardOrderLatestExpiredGetRequest was null or undefined when calling cardOrderLatestExpiredGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/latestExpired`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderLatestExpiredGetRequestToJSON(requestParameters.cardOrderLatestExpiredGetRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderLatestExpiredGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得最新超時卡片訂單
     */
    async cardOrderLatestExpiredGet(requestParameters: CardOrderLatestExpiredGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderLatestExpiredGetResponse> {
        const response = await this.cardOrderLatestExpiredGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得卡片訂單分頁
     */
    async cardOrderPageRaw(requestParameters: CardOrderPageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderPageResponse>> {
        if (requestParameters.cardOrderPageRequest === null || requestParameters.cardOrderPageRequest === undefined) {
            throw new runtime.RequiredError('cardOrderPageRequest','Required parameter requestParameters.cardOrderPageRequest was null or undefined when calling cardOrderPage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderPageRequestToJSON(requestParameters.cardOrderPageRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderPageResponseFromJSON(jsonValue));
    }

    /**
     * 取得卡片訂單分頁
     */
    async cardOrderPage(requestParameters: CardOrderPageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderPageResponse> {
        const response = await this.cardOrderPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 重新付款卡片訂單
     */
    async cardOrderRepayRaw(requestParameters: CardOrderRepayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderRepayResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderRepay.');
        }

        if (requestParameters.cardOrderRepayRequest === null || requestParameters.cardOrderRepayRequest === undefined) {
            throw new runtime.RequiredError('cardOrderRepayRequest','Required parameter requestParameters.cardOrderRepayRequest was null or undefined when calling cardOrderRepay.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}/repay`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderRepayRequestToJSON(requestParameters.cardOrderRepayRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderRepayResponseFromJSON(jsonValue));
    }

    /**
     * 重新付款卡片訂單
     */
    async cardOrderRepay(requestParameters: CardOrderRepayOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderRepayResponse> {
        const response = await this.cardOrderRepayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新卡片訂單
     */
    async cardOrderUpdateRaw(requestParameters: CardOrderUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardOrderUpdateResponse>> {
        if (requestParameters.cardOrderId === null || requestParameters.cardOrderId === undefined) {
            throw new runtime.RequiredError('cardOrderId','Required parameter requestParameters.cardOrderId was null or undefined when calling cardOrderUpdate.');
        }

        if (requestParameters.cardOrder === null || requestParameters.cardOrder === undefined) {
            throw new runtime.RequiredError('cardOrder','Required parameter requestParameters.cardOrder was null or undefined when calling cardOrderUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cardOrder/{cardOrderId}`.replace(`{${"cardOrderId"}}`, encodeURIComponent(String(requestParameters.cardOrderId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CardOrderToJSON(requestParameters.cardOrder),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardOrderUpdateResponseFromJSON(jsonValue));
    }

    /**
     * 更新卡片訂單
     */
    async cardOrderUpdate(requestParameters: CardOrderUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardOrderUpdateResponse> {
        const response = await this.cardOrderUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
