/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Transfer,
  TransferAddResponse,
  TransferConfirmRequest,
  TransferConfirmResponse,
  TransferGetResponse,
  TransferUpdateResponse,
} from '../models/index';
import {
    TransferFromJSON,
    TransferToJSON,
    TransferAddResponseFromJSON,
    TransferAddResponseToJSON,
    TransferConfirmRequestFromJSON,
    TransferConfirmRequestToJSON,
    TransferConfirmResponseFromJSON,
    TransferConfirmResponseToJSON,
    TransferGetResponseFromJSON,
    TransferGetResponseToJSON,
    TransferUpdateResponseFromJSON,
    TransferUpdateResponseToJSON,
} from '../models/index';

export interface TransferAddRequest {
    transfer: Transfer;
}

export interface TransferConfirmOperationRequest {
    transferId: number;
    transferConfirmRequest: TransferConfirmRequest;
}

export interface TransferGetRequest {
    transfer: Transfer;
}

export interface TransferUpdateRequest {
    transferId: number;
    transfer: Transfer;
}

/**
 * 
 */
export class TransferApi extends runtime.BaseAPI {

    /**
     * 新增轉帳
     */
    async transferAddRaw(requestParameters: TransferAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferAddResponse>> {
        if (requestParameters.transfer === null || requestParameters.transfer === undefined) {
            throw new runtime.RequiredError('transfer','Required parameter requestParameters.transfer was null or undefined when calling transferAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transfer`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferToJSON(requestParameters.transfer),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增轉帳
     */
    async transferAdd(requestParameters: TransferAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferAddResponse> {
        const response = await this.transferAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 確認轉帳(接收回調)
     */
    async transferConfirmRaw(requestParameters: TransferConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferConfirmResponse>> {
        if (requestParameters.transferId === null || requestParameters.transferId === undefined) {
            throw new runtime.RequiredError('transferId','Required parameter requestParameters.transferId was null or undefined when calling transferConfirm.');
        }

        if (requestParameters.transferConfirmRequest === null || requestParameters.transferConfirmRequest === undefined) {
            throw new runtime.RequiredError('transferConfirmRequest','Required parameter requestParameters.transferConfirmRequest was null or undefined when calling transferConfirm.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transfer/{transferId}/confirm`.replace(`{${"transferId"}}`, encodeURIComponent(String(requestParameters.transferId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferConfirmRequestToJSON(requestParameters.transferConfirmRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferConfirmResponseFromJSON(jsonValue));
    }

    /**
     * 確認轉帳(接收回調)
     */
    async transferConfirm(requestParameters: TransferConfirmOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferConfirmResponse> {
        const response = await this.transferConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得轉帳
     */
    async transferGetRaw(requestParameters: TransferGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferGetResponse>> {
        if (requestParameters.transfer === null || requestParameters.transfer === undefined) {
            throw new runtime.RequiredError('transfer','Required parameter requestParameters.transfer was null or undefined when calling transferGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transfer`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: TransferToJSON(requestParameters.transfer),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得轉帳
     */
    async transferGet(requestParameters: TransferGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferGetResponse> {
        const response = await this.transferGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新轉帳
     */
    async transferUpdateRaw(requestParameters: TransferUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferUpdateResponse>> {
        if (requestParameters.transferId === null || requestParameters.transferId === undefined) {
            throw new runtime.RequiredError('transferId','Required parameter requestParameters.transferId was null or undefined when calling transferUpdate.');
        }

        if (requestParameters.transfer === null || requestParameters.transfer === undefined) {
            throw new runtime.RequiredError('transfer','Required parameter requestParameters.transfer was null or undefined when calling transferUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transfer/{transferId}`.replace(`{${"transferId"}}`, encodeURIComponent(String(requestParameters.transferId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferToJSON(requestParameters.transfer),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferUpdateResponseFromJSON(jsonValue));
    }

    /**
     * 更新轉帳
     */
    async transferUpdate(requestParameters: TransferUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferUpdateResponse> {
        const response = await this.transferUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
