/* tslint:disable */
/* eslint-disable */
/**
 * order base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransferConfirmLog,
  TransferConfirmLogAddResponse,
} from '../models/index';
import {
    TransferConfirmLogFromJSON,
    TransferConfirmLogToJSON,
    TransferConfirmLogAddResponseFromJSON,
    TransferConfirmLogAddResponseToJSON,
} from '../models/index';

export interface TransferConfirmLogAddRequest {
    transferConfirmLog: TransferConfirmLog;
}

/**
 * 
 */
export class TransferConfirmLogApi extends runtime.BaseAPI {

    /**
     * 新增轉帳確認紀錄
     */
    async transferConfirmLogAddRaw(requestParameters: TransferConfirmLogAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferConfirmLogAddResponse>> {
        if (requestParameters.transferConfirmLog === null || requestParameters.transferConfirmLog === undefined) {
            throw new runtime.RequiredError('transferConfirmLog','Required parameter requestParameters.transferConfirmLog was null or undefined when calling transferConfirmLogAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/transferConfirmLog`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferConfirmLogToJSON(requestParameters.transferConfirmLog),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferConfirmLogAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增轉帳確認紀錄
     */
    async transferConfirmLogAdd(requestParameters: TransferConfirmLogAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferConfirmLogAddResponse> {
        const response = await this.transferConfirmLogAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
