/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgencyPlan,
  AgencyPlanAddResponse,
  AgencyPlanGetResponse,
  AgencyPlanUpdateResponse,
} from '../models/index';
import {
    AgencyPlanFromJSON,
    AgencyPlanToJSON,
    AgencyPlanAddResponseFromJSON,
    AgencyPlanAddResponseToJSON,
    AgencyPlanGetResponseFromJSON,
    AgencyPlanGetResponseToJSON,
    AgencyPlanUpdateResponseFromJSON,
    AgencyPlanUpdateResponseToJSON,
} from '../models/index';

export interface AgencyPlanAddRequest {
    agencyPlan: AgencyPlan;
}

export interface AgencyPlanGetRequest {
    agencyPlan: AgencyPlan;
}

export interface AgencyPlanUpdateRequest {
    agencyPlanId: number;
    agencyPlan: AgencyPlan;
}

/**
 * 
 */
export class AgencyPlanApi extends runtime.BaseAPI {

    /**
     * 新增代理方案
     */
    async agencyPlanAddRaw(requestParameters: AgencyPlanAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyPlanAddResponse>> {
        if (requestParameters.agencyPlan === null || requestParameters.agencyPlan === undefined) {
            throw new runtime.RequiredError('agencyPlan','Required parameter requestParameters.agencyPlan was null or undefined when calling agencyPlanAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agencyPlan`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyPlanToJSON(requestParameters.agencyPlan),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyPlanAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增代理方案
     */
    async agencyPlanAdd(requestParameters: AgencyPlanAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyPlanAddResponse> {
        const response = await this.agencyPlanAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得代理方案
     */
    async agencyPlanGetRaw(requestParameters: AgencyPlanGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyPlanGetResponse>> {
        if (requestParameters.agencyPlan === null || requestParameters.agencyPlan === undefined) {
            throw new runtime.RequiredError('agencyPlan','Required parameter requestParameters.agencyPlan was null or undefined when calling agencyPlanGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agencyPlan`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyPlanToJSON(requestParameters.agencyPlan),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyPlanGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得代理方案
     */
    async agencyPlanGet(requestParameters: AgencyPlanGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyPlanGetResponse> {
        const response = await this.agencyPlanGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新代理方案
     */
    async agencyPlanUpdateRaw(requestParameters: AgencyPlanUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyPlanUpdateResponse>> {
        if (requestParameters.agencyPlanId === null || requestParameters.agencyPlanId === undefined) {
            throw new runtime.RequiredError('agencyPlanId','Required parameter requestParameters.agencyPlanId was null or undefined when calling agencyPlanUpdate.');
        }

        if (requestParameters.agencyPlan === null || requestParameters.agencyPlan === undefined) {
            throw new runtime.RequiredError('agencyPlan','Required parameter requestParameters.agencyPlan was null or undefined when calling agencyPlanUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agencyPlan/{agencyPlanId}`.replace(`{${"agencyPlanId"}}`, encodeURIComponent(String(requestParameters.agencyPlanId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyPlanToJSON(requestParameters.agencyPlan),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyPlanUpdateResponseFromJSON(jsonValue));
    }

    /**
     * 更新代理方案
     */
    async agencyPlanUpdate(requestParameters: AgencyPlanUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyPlanUpdateResponse> {
        const response = await this.agencyPlanUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
