/* tslint:disable */
/* eslint-disable */
/**
 * agency base
 * This is my API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Agency,
  AgencyAddResponse,
  AgencyGetResponse,
  AgencyUpdateResponse,
} from '../models/index';
import {
    AgencyFromJSON,
    AgencyToJSON,
    AgencyAddResponseFromJSON,
    AgencyAddResponseToJSON,
    AgencyGetResponseFromJSON,
    AgencyGetResponseToJSON,
    AgencyUpdateResponseFromJSON,
    AgencyUpdateResponseToJSON,
} from '../models/index';

export interface AgencyAddRequest {
    agency: Agency;
}

export interface AgencyGetRequest {
    agency: Agency;
}

export interface AgencyUpdateRequest {
    agencyId: number;
    agency: Agency;
}

/**
 * 
 */
export class AgencyApi extends runtime.BaseAPI {

    /**
     * 新增代理
     */
    async agencyAddRaw(requestParameters: AgencyAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyAddResponse>> {
        if (requestParameters.agency === null || requestParameters.agency === undefined) {
            throw new runtime.RequiredError('agency','Required parameter requestParameters.agency was null or undefined when calling agencyAdd.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agency`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyToJSON(requestParameters.agency),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyAddResponseFromJSON(jsonValue));
    }

    /**
     * 新增代理
     */
    async agencyAdd(requestParameters: AgencyAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyAddResponse> {
        const response = await this.agencyAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得代理
     */
    async agencyGetRaw(requestParameters: AgencyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyGetResponse>> {
        if (requestParameters.agency === null || requestParameters.agency === undefined) {
            throw new runtime.RequiredError('agency','Required parameter requestParameters.agency was null or undefined when calling agencyGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agency`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyToJSON(requestParameters.agency),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyGetResponseFromJSON(jsonValue));
    }

    /**
     * 取得代理
     */
    async agencyGet(requestParameters: AgencyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyGetResponse> {
        const response = await this.agencyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新代理
     */
    async agencyUpdateRaw(requestParameters: AgencyUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgencyUpdateResponse>> {
        if (requestParameters.agencyId === null || requestParameters.agencyId === undefined) {
            throw new runtime.RequiredError('agencyId','Required parameter requestParameters.agencyId was null or undefined when calling agencyUpdate.');
        }

        if (requestParameters.agency === null || requestParameters.agency === undefined) {
            throw new runtime.RequiredError('agency','Required parameter requestParameters.agency was null or undefined when calling agencyUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agency/{agencyId}`.replace(`{${"agencyId"}}`, encodeURIComponent(String(requestParameters.agencyId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AgencyToJSON(requestParameters.agency),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgencyUpdateResponseFromJSON(jsonValue));
    }

    /**
     * 更新代理
     */
    async agencyUpdate(requestParameters: AgencyUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgencyUpdateResponse> {
        const response = await this.agencyUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
